### ISSUE TITLE
Propozycja: Zachowanie filtrów przy zmianie semestru

### ISSUE THREAD

**Issue by JMendyk** [iiuni/projektzapisy#1024]
Miłym usprawnieniem "jakości życia" użytkowania systemu byłoby, gdyby w zakładce "Przedmioty" filtry - tagów, rodzaju przedmiotu - nie były resetowane przy zmianie semestru. Aktualnie poszukiwanie przedmiotów o wybranym tagu w poprzednich latach jest bardzo uciążliwe.

Z góry dziękuję za rozważenie propozycji.

**Comment by jasiekmarc** [comment]
To by faktycznie było przydatne, chociaż niestety nie będzie takie proste. Nawet bardziej użyteczne byłoby to w przypadku, gdy filtrujemy przedmioty i klikamy na jakiś. Również na liście studentów/pracowników takie zachowanie wartości filtrów po kliknięciu byłoby wygodne.

Prawdopodobnie najlepszym rozwiązaniem byłoby jakoś obustronnie powiązać filtry z parametrami GET.
