### ISSUE TITLE
Propozycje nowych funkcji i usprawnień

### ISSUE THREAD

**Issue by kamilonline** [iiuni/projektzapisy#1030]
### Propozycje nowych funkcji i usprawnień dla systemu zapisów

1. Opuszczanie w kolejce w przypadku braku punktów ECTS
Obecnie można zapisywać się na dodatkowe przedmioty nawet jeśli nie mamy wystarczającej liczby dostępnych punktów ECTS. Jeśli jednak zwolni się miejsce przed odblokowaniem dostępu do przekroczenia puli 35 ECTS-ów zostaniemy usunięci z kolejki i wylądujemy na jej końcu.
Rozwiązaniem by było przepuszczanie w kolejce osób, których poziom ECTS-ów pozwala na zapisanie się na przedmiot. Wtedy koledzy, którzy później wpisali się do kolejki, pojawią się, a jak zwolni się limit, będziemy nadal mieli szansę na zapisanie się.

2. Kolumny w planie zajęć
Gdy w jednym momencie jesteśmy zapisani na więcej niż jeden przedmiot, kolumna dzieli się na x części we wszystkich częściach, przez co pojedyncze przedmioty w innych godzinach również się kurczą i stają się tym samym nieczytelne.

3. Informacja o obecnym miejscu w kolejce
Aktualnie nasze miejsce w kolejce możemy sprawdzić, klikając na listę uczestników danego kursu. Można umieścić je natomiast np. przy priorytecie albo przy liczbie osób w kolejce.

**Comment by kamilonline** [comment]
Następna rzecz. Przy kolejce w instrukcji napisane im wyższa liczba tym większy priorytet. Takie sformułowanie jest mylące, gdyż można łatwo uznać, że wyższa liczba stoi wyżej na liście, czyli 1 to najwyższy priorytet.

Proponuję zmianę na "większa liczba", albo "priorytety to liczby ustawione malejąco"

**Comment by jasiekmarc** [comment]
W sprawie pierwszej się z Panem nie zgadzam. W supermarkecie się zdarzają takie ekipy, że jeden stoi w kolejce do kasy, a reszta mu przynosi zakupy. Nie lubi się takich. Kolejka przestaje być wtedy kolejką.

W pozostałych trzech sprawach, zachęcam Pana do zaproponowania Pull Requesta (szczególnie w drugiej, bo ja tego nie umiem elegancko rozwiązać).

Na przyszłość proszę tworzyć osobne _issues_ dla osobnych spraw.
