### ISSUE TITLE
Praca inżynierska 3 studentów

### ISSUE THREAD

**Issue by wzychla** [iiuni/projektzapisy#1049]
Zgodnie z informacją na stronie https://ii.uni.wroc.pl/dla-studenta/prace-dyplomowe praca inżynierska może być realizowana przez 3 studentów:

> W przypadku pracy zespołowej oczekiwany rozmiar jest większy o 75% w przypadku zespołów dwuosobowych oraz o 150% w przypadku zespołów trzyosobowych. 

Aktualnie jednak system nie pozwala przypisać 3 studentów do pracy a próba zapisu kończy się błędem walidatora "Możesz przypisać maksymalnie 2 studentów". 

Proszę o poluzowanie walidatora, dopuszczenie wyboru 3 studentów.
pozdrawiam
Wiktor Zychla

**Comment by mbuszka** [comment]
W porozumieniu z zastępcą dyrektora do spraw dydaktycznych, samodzielnie można dodać maksymalnie jednego studenta do pracy dyplomowej, natomiast by dodać ich więcej należy zwrócić się do niego.
W nowej wersji, która niebawem powinna się ukazać, komunikat walidatora będzie odpowiadał tym wymaganiom.
