### ISSUE TITLE
Raportowanie błędu 404 do Rollbara

### ISSUE THREAD

**Issue by mbuszka** [iiuni/projektzapisy#1098]
Zostaliśmy zaatakowani przez jakiegoś bota który ciągle próbuje pobrać nieistniejącą stronę (w aplikacji courses). Nasza aplikacja zwraca błąd 404, który jest następnie raportowany do rollbara. Mamy limit 10 000 wystąpień miesięcznie który został zjedzony przez bota w ciągu kilku dni. Należy poprawić konfigurację middleware rollbara tak aby nie dopuścić więcej do takiej sytuacji. Pytanie czy da się zrobić to lepiej niż ignorować wszystkie wystąpienia błędu 404.

**Comment by jasiekmarc** [comment]
https://github.com/iiuni/projektzapisy/blob/122c11619fe9262bf5ee3802046769674d10b25d/zapisy/zapisy/settings.py#L329
