### ISSUE TITLE
Theses should not be editable after they have been accepted

### ISSUE THREAD

**Issue by mbuszka** [iiuni/projektzapisy#1186]
Additionally creator of a thesis should be able to change status back to `BEING_EVALUATED`

**Comment by akucintavalent** [comment]
@mbuszka Okay, czyli robimy tak, że nie można zmienić tytułu, opisu, maks. liczby studentów oraz niektórych innych pól, ale można ponownie wybrać samych studentów, oraz można będzie zmienić status na poddana pod głosowanie. Jeśli coś zapomniałem, byłoby fajnie, gdyby Pan mi przypomniał.

**Comment by mbuszka** [comment]
@akucintavalent  Wymagania się zgadzają.
