### ISSUE TITLE
Przycisk "Pokaż tylko niezarezerwowane prace" w pracach dyplomowych nie działa

### ISSUE THREAD

**Issue by bartoszjanbednarczyk** [iiuni/projektzapisy#1335]
Po kliknięciu w przycisk "Pokaż tylko niezarezerwowane prace" w https://zapisy.ii.uni.wroc.pl/theses/ dalej widać zarezerwowane prace.
![image](https://user-images.githubusercontent.com/77882424/183363938-a1b42fbe-7b00-4c0b-8377-6b5735833387.png)

**Comment by lgpawel** [comment]
_Technicznie_ być może wszystko jest w porządku – przykładowo dla tych dwóch tematów, które widać na screenie, termin rezerwacji już upłynął (stąd zresztą nazwiska na szaro) i rezerwację w związku z tym należy rozumieć jako nieważną. Ale oczywiście intencja tej kontrolki (ewidentnie nieco rozmijająca się z jej dosłownym opisem) jest taka, żeby pokazywać tematy "do wzięcia" i np. te oznaczone jako obronione na pewno powinny być przez nią ukrywane.

**Comment by Brychlikov** [comment]
Jest tak, jak Pan podejrzewał - technicznie wszystko jest w porządku, tematy widoczne na screenie były zarezerwowane, ale ich rezerwacje wygasły - stąd wyszarzone nazwiska. 

Widzę dwa rozwiązania: 
- Niech przycisk pokazuje tylko prace "gotowe do wzięcia", tj. takie, które nigdy nie zostały zarezerwowane. Implementowane przez #1469
- Niech przycisk pokazuje tematy, które da się wziąć, ale być może z pewnym wysiłkiem. Chcielibyśmy pokazywać też tematy porzucone, czyli takie, których rezerwacje wygasły i obecnie nikt ich nie pisze. Nie wiem, czy jest to wykonalne - prawie na pewno nie przy obecnej wiedzy systemu. Nie znam też procedur porzucania tematów prac, potrzebowałbym w tym temacie konsultacji.

Są jeszcze rozwiązania pośrednie, np. ukrycie z obecnego widoku prac obronionych, a pozostawienie tych w realizacji, ale nie wydają mi się szczególnie użyteczne.
