### ISSUE TITLE
admin/courses/course/ not trigerring do_rearanged

### ISSUE THREAD

**Issue by Kostero** [iiuni/projektzapisy#139]
[10:10]
chodzi o zmianę limitów grup

[10:11]  
Jeśli zmienia się limity pojedynczej grupy poprzez: fereol_admin/courses/group/ to jest spoko

[10:12]  
ale jeśli zmienia się limity grup 'masowo' dla całego przedmiotu poprzez `fereol_admin/courses/course/` to niestety nie uruchamiane jest żadne do_rearanged

[10:13]  
nie wiedziałem że można tak masowo zmieniać limity w tym miejscu - mabi tego dzisiaj używała i były problemy, bo ludzi z kolejek nie poprzerzucało a inni się zapisywali na ich miejsce

**Comment by jasiekmarc** [comment]
Fixed by #502.
