### ISSUE TITLE
Informacje o zmianie statusu rezerwacji sali

### ISSUE THREAD

**Issue by ljez** [iiuni/projektzapisy#1394]
Rezerwacje sal, przynajmniej te w kategorii "Wydarzenie" muszą zostać zatwierdzone (swoją droga, ciekawe przez kogo i czemu brak o tym informacji..).  Obecnie system nie informuje w żaden sposób o zmianach statusu rezerwacji (np. zaakceptowaniu) a wydaje się, że powinien wysłać email z powiadomieniem o zmianie.

**Comment by lgpawel** [comment]
To powinno być stosunkowo proste – należy dodać nowy rodzaj powiadomień (które również skutkują wysłaniem maila zgodnie z ustawieniami użytkownika) i spiąć go z miejscem w kodzie, gdzie odklikuje się decyzję o zatwierdzeniu.

> ciekawe przez kogo

Ogólnie przez dowolną osobę z uprawnieniami administratora Django (w praktyce najczęściej zapewne przez `asm`). Swoją drogą: wydarzenia zakładane przez tych użytkowników chyba są natychmiastowo zatwierdzone (o czym ostatnio się przypadkiem przekonałem) i taki scenariusz **nie** powinien skutkować powiadomieniem.
