### ISSUE TITLE
Rozjeżdżanie tabeli na stronie zarządzania rezerwacjami

### ISSUE THREAD

**Issue by Papunio** [iiuni/projektzapisy#1416]
Przy wystarczająco długim opisie wydarzenia psuje się układ strony i nie widać przez to lokalizacji wydarzenia.

![rozjechanie](https://user-images.githubusercontent.com/64105446/210391542-7c4ae8b5-5fc9-4dad-81ae-385c1c7ff96c.png)
![rozjechanie2](https://user-images.githubusercontent.com/64105446/210391551-9f81e164-17de-4bee-bb90-ce5ddee34203.png)

**Comment by MusicFreak456** [comment]
Dla ścisłości: co najmniej jedno nieprawdopodobnie długie słowo w opisie psuje layout strony.
