### ISSUE TITLE
Limit 35 ECTS

### ISSUE THREAD

**Issue by Wojtek130** [iiuni/projektzapisy#1449]
Limit 35 ECTS nie działa, tzw.  można się zapisać bez problem na przedmioty, przekraczając limit 35 ectsów, przed jego zniesieniem.

**Comment by pitcer** [comment]
Wygląda na to, że w bazie danych w dacie zniesienia limitu został ustawiony poprzedni rok. Po zmianie na prawidłowy limit ponownie działa.

**Comment by pitcer** [comment]
Pisałem w sprawie tego problemu do Pana Witkowskiego i dziś rano zmienił datę na poprawną. Przed chwilą sprawdziłem, że limit faktycznie już działa, więc myślę, że można to zamknąć.
