### ISSUE TITLE
Niedociągnięcie w widoku listy studentów zapisanych na przedmiot

### ISSUE THREAD

**Issue by TWolczanski** [iiuni/projektzapisy#1478]
W widoku listy studentów zapisanych na przedmiot, osiągalnym przez kliknięcie przycisku "Lista", panel po prawej stronie wygląda zdecydowanie nie tak, jak byśmy chcieli:

![Screenshot from 2023-03-29 23:57:57](https://user-images.githubusercontent.com/73614115/228676964-b50aaa54-7e2b-40d0-a8e5-420c53638a90.png)

Można albo usunąć resztki tego panelu, albo dodać do niego brakujące elementy.

**Comment by lgpawel** [comment]
Tak, to zdecydowanie niedoróbka w tym dosyć nowym _feature_ jakim jest zbiorczy widok listy wszystkich osób zapisanych / zakolejkowanych do grup zajęciowych określonego typu (albo wszystkich grup zajęciowych, tam też jest ten problem). "Oczywiście" rozwiązaniem spójnym z innymi widokami na podstronach z `/courses/` będzie "wypełnienie" tego dropdownu, ale też *wyświetlenie poniżej listy przedmiotów*, por. choćby widok listy osób z pojedynczej grupy. Biorąc pod uwagę powtarzanie się identycznej zawartości na wszystkich ww. podstronach, na pewno dobrze byłoby mieć ją w wydzielonym _template_.
