### ISSUE TITLE
Code smell w jsie od filtrowania

### ISSUE THREAD

**Issue by florczakraf** [iiuni/projektzapisy#187]
https://github.com/lewymati/projektzapisy/blame/master-dev/zapisy/site_media/js/common/listFilter.js#L359

**Comment by jasiekmarc** [comment]
Do zamknięcia przy okazji przepisywania filtrów.

**Comment by Arusekk** [comment]
Kod przeniesiony. Permalink:
https://github.com/iiuni/projektzapisy/blob/5e0835b51aebab067d26130aecb390b36864adc1/zapisy/assets/legacy/js/common/listFilter.js#L359
