### ISSUE TITLE
Refactor records_list.html

### ISSUE THREAD

**Issue by kuba-kazimierczak** [iiuni/projektzapisy#221]
Mamy dwa pliki records_list.html, jeden siedzi sobie w zapisy/templates, drugi w zapisy/apps/enrollment/records, jeden includuje drugi, a w zapisy/apps/enrollments/records mamy symlinka (!) na zapisy/templates. Ogólnie: clusterfuck. Materiał na osobny PR

**Comment by jasiekmarc** [comment]
Rozwiązane przez #502.
