### ISSUE TITLE
Mnóstwo nieużywanych template'ów i views w aplikacji offer

### ISSUE THREAD

**Issue by user-45-20** [iiuni/projektzapisy#229]
Dla przykładu, `zapisy/templates/offer/main.html` w ogóle nie jest używany. Jest ich więcej. Ponadto wszyscy extendują offer/base.html, która zawiera listę przedmiotów tylko po to, żeby ją nadpisać i usunąć.

**Comment by jasiekmarc** [comment]
Ze wszystkich tych template'ów powinien pozostać prawdopodobnie tylko `base.html`. Aplikacja `offer/desiderata` powinna mieć swoje template'y w swoim katalogu aplikacji.

**Comment by jasiekmarc** [comment]
Zamykamy w związku z #904.
