### ISSUE TITLE
Uporządkowanie oceny zajęć

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#237]
Zadanie polega na uporządkowaniu oceny zajęć.
W skład zadania wchodzi:
- [ ] Stworzenie dokumentacji obecnego systemu
- [x] Pozbycie się enigmatycznej ankiety ogólnej "Projekt"
- [ ] https://tracker-zapisy.ii.uni.wroc.pl/issues/9
- [ ] https://tracker-zapisy.ii.uni.wroc.pl/issues/30
- [ ] https://tracker-zapisy.ii.uni.wroc.pl/issues/34
- [ ] https://tracker-zapisy.ii.uni.wroc.pl/issues/33
- [ ] Stworzenie funkcjonalności publicznych raportów zbiorczych jak na stronie http://ocena.ii.uni.wroc.pl/administracja/ad.phtml
- [ ] Dodanie wygodnego widoku, w którym DDD może obejrzeć wszystkie ankiety dotyczące danego pracownika

**Comment by jasiekmarc** [comment]
Dwie części oceny zajęć są przepisywane przez panów @Acee11 i @mkochanowski.
