### ISSUE TITLE
przeniesienie importów na początki plików

### ISSUE THREAD

**Issue by Marqin** [iiuni/projektzapisy#250]
Jak zaproponowano w dyskusji pod PR upgradu do 1.8 - https://github.com/iiuni/projektzapisy/pull/223#discussion_r147584605 - tworze nowy issue na usunięcie importów, które występują wewnatrz plików, a nie na ich początkach.

**Comment by jasiekmarc** [comment]
W nowym kodzie nigdy nie robimy importów poza nagłówkiem. Problem powoli znika.
