### ISSUE TITLE
Błędy w podglądzie edycji przedmiotu

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#26]
Np. `/courses/algebra_1516` 

> (Studenci w grupach: , studenci bez grupy: )
- [ ] zrozumieć widok `course` z `apps/enrollment/courses/views.py`
- [ ] w miarę możliwości pozbyć się SQLa na rzecz zapytań django
- [ ] naprawić błąd
- [ ] przenieść większość kodu z widoku do odpowiednich metod modeli

**Comment by jasiekmarc** [comment]
Widok przedmiotu przepisany w #502.
