### ISSUE TITLE
Creating polls for groups not working 

### ISSUE THREAD

**Issue by Notechus** [iiuni/projektzapisy#272]
When you open **<root_url>/grade/poll/managment/groups_without_polls/** and there are existing elements on page and you click on one of them you will be redirected to **<root_url>/grade/poll/managment/poll_create/<id>**. The template of the page is 'ajax_poll_create.html' and is only <form> element alone. Adding sections to the form  is not working on 1.8 on dev environment. 

This is the page layout:

<img width="703" alt="screen shot 2017-11-18 at 21 19 52" src="https://user-images.githubusercontent.com/12254026/32984404-494ee904-cca6-11e7-8be1-4b9fd15d8512.png">

**Comment by jasiekmarc** [comment]
Do załatwienia przy okazji przepisywania aplikacji **grade/poll**.
