### ISSUE TITLE
Hardcode semestru w widoku 'students' (aplikacja 'statistics')

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#32]
@florczakraf na slacku:

> Jakiś hardcode semestru w zapytaniu (za jakiś czas przyjdzie pytanie z góry: "A dlaczego są cały czas stare statystyki?"):
> https://github.com/lewymati/projektzapisy/blob/master/zapisy/apps/statistics/views.py#L21-L29

**Comment by jasiekmarc** [comment]
Fixed by #502.
