### ISSUE TITLE
Puste filtry w egzaminach: template schedule/session.html error

### ISSUE THREAD

**Issue by mbuszka** [iiuni/projektzapisy#415]
##### Sale/Egzaminy 
Template odwołuje się do zmiennej `exams.form` próbując stworzyć formularz filtrowania egzaminów, ale nie ma ona takiego pola. W efekcie generowany jest error, a strona zawiera pusty formularz

**Comment by jasiekmarc** [comment]
W #603 formularz jest usunięty. Zamykam.
