### ISSUE TITLE
Walidacja modeli

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#47]
Prawie wszystkie modele powinny mieć przeciążone metody `clean()`

Wg. aplikacji:
- [ ] enrollment/courses
- [ ] enrollment/records
- [ ] offer
- [ ] schedule
- [ ] users

Przydałoby się najpierw napisać testy.

**Comment by jasiekmarc** [comment]
Nie rozumiem, czemu miałyby mieć.
