### ISSUE TITLE
Prawa dostępu do widoków

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#48]
W zeszłym semestrze były problemy z dostępem, niektórzy użytkownicy mieli dostęp do widoków, których nie powinni widzieć

Zadania:
- [ ]  Opisać sposób w jaki system sprawdza dostęp użytkownika do widoku i jesli zajedzie taka potrzeba poprawić go
- [ ]  Upewnić się, że wszystkie widoki które powinny być dostępne tylko dla pracowników są niedostępne dla studentów

**Comment by jasiekmarc** [comment]
W mojej opinii problem w zasadzie nie istnieje.
