### ISSUE TITLE
Usunięcie/oznakowanie głosu na przedmiot w zakładce "Pokaż mój głos", jeśli przedmiot został wycofany z oferty

### ISSUE THREAD

**Issue by chevrette** [iiuni/projektzapisy#548]
Zmiana statusu przedmiotu z "poddany pod głosowanie" na "wycofany z oferty" nie usuwa głosu z zakładki "pokaż mój głos"(z "głosuj" i "podsumowanie" przedmiot znika).

**Comment by jasiekmarc** [comment]
Moim zdaniem to dobrze, że przedmiot pojawia się w podsumowaniu głosowania. Być może mógłby być wyróżniony jako wycofany.
