### ISSUE TITLE
DoS przy listowaniu kluczy

### ISSUE THREAD

**Issue by Acee11** [iiuni/projektzapisy#582]
Request na `/grade/ticket/keys_list` dosuje serwer. Prawdopodobnie przez to, że wysyłane jest wtedy dość duże zapytanie do bazy danych o wszystkie klucze publiczne, co sprawia że po zaledwie 10 requestach serwer odpowiada `504`.

**Comment by jasiekmarc** [comment]
Zamykam w związku z #689.
