### ISSUE TITLE
Typ grupy tutoring

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#584]
Cahir potrzebuje nowego typu grupy o nazwie "Tutoring". Wstępnie ustalone z MaBi.
W trakcie przepisywania do usos-a zajęcia z tutoringu będą naliczane do pensum prowadzącego, ale nie będą generowane protokoły zaliczeniowe. Dotyczy przedmiotów takich jak: "Kształtowanie ścieżki akademicko-zawodowej".

**Comment by cahirwpz** [comment]
Jakieś postępy w tej sprawie?

**Comment by jasiekmarc** [comment]
Żadnego. Ja nic nie rozumiem z tego issue i nikt mi nie odpowiedział na pytanie.

Czy chodzi po prostu o dodanie typu grupy w modelu, czy trzeba robić coś więcej? Jakie znaczenia ma ta uwaga o pensum i protokołach?

**Comment by cahirwpz** [comment]
Nie wiem czy uwaga o pensum i protokołach ma jakikolwiek poważniejszy wpływ na SZ.
Z tego co rozumiem tego typu dane są ważne tylko w USOS – co nie zmienia faktu,
że powinienem móc łatwo ją wyekstrahować z SZ.

Wydaje mi się, że dodanie typu grupy w modelu i wystawienie tego w UI wystarczy.

**Comment by jasiekmarc** [comment]
To ponawiam moje pytanie: Czy w interfejsie między Systemem Zapisów i Schedulerem też ma istnieć ten typ grupy? Czy będzie również dodany do schedulera (@wiura)?

**Comment by wiura** [comment]
Ogólnie mówiąc, nowy typ grupy należy wszędzie dodać. Zazwyczaj są to małe zmiany w kodzie/bazie i nie są zbyt skomplikowane, ale jest wiele miejsc, o których trzeba pamiętać.

* jeśli chodzi o SZ to:
  * trzeba dodać nową grupę
  * nowa grupa powinna poprawnie się wyświetlać w interfejsach
  * poprawić importer z schedulera, aby wiedział o istnieniu nowego rodzaju grupy
  * prawdopodobnie poprawić eksporter do usosa (pensum, itp, ale ja dokładnie nie pamiętam)
* jeśli chodzi o schedulera to
     * trzeba ustalić z mabi (albo tu) skrót i nazwę dla nowego rodzaju grupy, bo przydziały pochodzą od mabi, obecne mamy:
         w (wykład), p (pracownia), c (ćwiczenia), s (seminarium), r (ćwieczenio-pracownia), e (repetytorium), o (projekt)
     * trzeba ustalić pensum, domyślny czas trwania takiej grupy (np ćwiczenia domyślnie trwają 2 godziny), domyślną liczbę osób w grupie, domyślny typ sali (sala ćwiczeniowa/wykładowa/pracownia)
     * trzeba dodać nowy rodzaj grupy do schedulera (interfejsy, tworzenie przydziałów itp)
