### ISSUE TITLE
Niepoprawne wyświetlanie głosowania przy wykorzystanych wszystkich punktach

### ISSUE THREAD

**Issue by kuba-kazimierczak** [iiuni/projektzapisy#593]
Opis sytuacji: głosowałem w terminie głosowania, później w korekcie. Wykorzystałem wszystkie punkty.
Mimo to system pozwala mi wejść na zakładkę "Głosuj" i oddać głos, jednak później wyrzuca błąd: https://gyazo.com/90d3bf9f41bb2cf5cb23d64dd8d066c7
problemy są dwa:
* system nie powinien pozwalać wejść na zakładkę głosuj, jeżeli już nie mam punktów
* system nie powinien wyświetlać "wykorzystane punkty - 3 z 0" (przypuszczam, że chodzi o trzy punkty, które oddałem w korekcie na nowy przedmiot)

**Comment by Nerd911** [comment]
Co proponujesz zamiast tego drugiego? "Przekroczono limit o 3"?
