### ISSUE TITLE
Umożliwienie tymczasowej zmiany szablonu powiadomień mailowych do studentów

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#596]
Obecnie, aby wysłać maila studentom, np. o otwarciu oceny zajęć, mamy do dyspozycji taki formularz (/notifications)
![image](https://user-images.githubusercontent.com/8168856/52087403-a2a60200-25a9-11e9-95a0-c9bdb7e1fc1d.png).

Czasem przydaje się jednak lekko zmodyfikować treść komunikatu, np. dodać datę zakończenia oceny zajęć. Aby to zrobić, muszę tymczasowo na produkcji modyfikować pliki templatów, np.
https://github.com/iiuni/projektzapisy/blob/master-dev/zapisy/apps/notifications/templates/notifications/grade-start.html

Przydałaby się możliwość modyfikacji tego template-u przed kliknięciem przycisku "Wyślij".
Wyobrażam sobie takie dodatkowe pole tekstowe przed przyciskiem.

P. S. Nie wiem jak do tej sprawy podchodzić będzie nowy system notyfikacji (@Asgavar ?).

**Comment by jasiekmarc** [comment]
Nowy system powiadomień w ogóle nie ma tej funkcji (wysyłania maili ręcznie).
