### ISSUE TITLE
Wielokrotne klucze do oceny zajęć.

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#598]
Administrator może wygenerować w jednym semestrze wiele kluczy do oceny. Powoduje to problemy przy pobieraniu kluczy przez studentów (takie jak: #597).

Rekomendacją dla administratora jest, by przed wygenerowaniem nowych kluczy wyrzucić stare (https://github.com/iiuni/projektzapisy/wiki/Uruchamianie-oceny-zaj%C4%99%C4%87#uwagi), ale łatwo o tym zapomnieć. Dlatego unikalność klucza powinna być wymuszona więzem w bazie/modelu.

**Comment by kuba-kazimierczak** [comment]
Myślę, że warto by też w skrypcie `create_keys` sprawdzać taką sytuację i wykasowywać stare klucze przy generowaniu nowych.

Być może w ramach tego issue wrzucić też jakiś drobny rework skryptów `create_polls`/`create_keys`? `create_polls` ma whardkodowane ID usera, który jest autorem ankiet (zmienna nazywa się `prych`, tak naprawdę jest to pani Kanarek). Nie wiem też, do czego ten autor ankiet jest używany - być może jest to pole przestarzałe, które już do niczego nie służy (fakt, że w każdej ankiecie ustawiane jest na już nieaktywnego użytkownika by to sugerował).

**Comment by jasiekmarc** [comment]
Zamknięte dzięki #689.
