### ISSUE TITLE
Nazwa przedmiotu wyświetlana w języku ustawionym w przeglądarce

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#611]
Większość przedmiotów ma w bazie nazwy w dwóch językach — polskim i angielskim. Nazwa przedmiotu wyświetla się użytkownikom w zależności od języka ich przeglądarki.
![image](https://user-images.githubusercontent.com/5896456/52575408-721e5d80-2e1e-11e9-9d24-57a1dd918bd9.png)
![image](https://user-images.githubusercontent.com/5896456/52575382-629f1480-2e1e-11e9-8b0a-ecde5ab5e4a1.png)

Użytkownicy często są tym bardzo skonfundowani.

**Comment by jasiekmarc** [comment]
Co gorsza, dotyczy to też formularza edycji przedmiotu.
![image](https://user-images.githubusercontent.com/5896456/52576008-94fd4180-2e1f-11e9-9c79-47fb423017e3.png)

**Comment by kuba-kazimierczak** [comment]
Nasz framework do lokalizacji - `django-modeltranslation` - instaluje middleware, który patrzy na `Accept-Language`, i na tej podstawie wybiera wersję językową, stąd problem

**Comment by jasiekmarc** [comment]
Naprawione przez #694
