### ISSUE TITLE
Typy grup zdefiniowane w niepraktycznej krotce.

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#612]
Grupa zajęciowa może być jednego z wielu typów _(wykład, ćwiczenia, pracownia, …)_. Typy te są zdefiniowane w tej linijce:
https://github.com/iiuni/projektzapisy/blob/dbadff9a81bc3de87a38c1afe944654042eec488/zapisy/apps/enrollment/courses/models/group.py#L15

Odniesienie się do typu grupy — na przykład sprawdzenie, czy jest wykładem — wymaga porównania pola `type` z nic nie mówiącą stałą, taką jak `'1'` dla wykładu. Lepiej by było zamienić tę definicję na Choicesenum, jak opisano tutaj:
https://python-choicesenum.readthedocs.io/en/latest/readme.html#django

**Comment by Clechay** [comment]
Chciałbym się przypisać chociaż jeszcze nie jestem członkiem zespołu na Githubie
