### ISSUE TITLE
Usunięcie relacji "teachers" z modelu Course

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#64]
Moim zdaniem relacja teachers z modelu Course powinna zostać usunięta.
Ta sama informacja przechowywana jest w Group.teacher, można się do niej dostać wykonując tą samą liczbę zapytań, na tabeli o tym samym rozmiarze.

**Comment by barnij** [comment]
Pull request https://github.com/iiuni/projektzapisy/pull/654
