### ISSUE TITLE
Refactor masowej wysyłki maili

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#642]
Z obecnym wysyłaniem powiadomień mailowych jest kilka problemów.
1) maile wysyłane są osobno do każdego studenta. Powoduje to, że przy wysyłce >4 maili dziennie przekraczamy limit liczby wiadomości narzucony przez Google (2000 wiadomości na dzień). 
Obecnie jest to rozwiązane w brutalny sposób: w cronie co 5 minut mamy: `./manage.py retry_deferred && ./manage.py send_mail`, czyli spamujemy Google aż nam odblokuje się limit. Na razie działa, ale to zdecydowanie nie jest właściwe rozwiązanie.

2) Wygląda na to, że dotychczasowa implementacja (katalog `mailer` w głównym folderze projektu zapisów), została skopiowana żywcem z wcześniejszej wersji https://github.com/pinax/django-mailer, oraz poddana modyfikacjom. Wydaje mi się to ekstremalnie nieeleganckie.

Proponowane rozwiązania:
Ad.1.: wysyłanie jednej wiadomości do wielu nadawców (UDW). Tutaj chyba mamy limit 500 odbiorców na wiadomość, więc trzeba wysłać kilka wiadomości. Implementacja powinna być elastyczna, aby móc szybko dostosowywać system do zmieniającej się polityki Google.
ADDENDUM: Google ma też limit na "Liczbę zewnętrznych adresatów na dzień", równy 3000. Powyższe rozwiązanie chyba jednak tego nie obejdzie. Dlatego można rozważyć stworzenie grupy dyskusyjnej i komunikowanie poprzez nią. Potrzebny jest głębszy research na ten temat.

Ad.2.: być może warto użyć niedawno wprowadzonego do naszego projektu django-rq. Ewentualnie rozważyć inne biblioteki wysyłania maili dedykowane dla Django. Implementacja powinna być elastyczna, tak by łatwo można było zmieniać konfiguracje, by zaspokoić zmieniające się limity wysyłania Google: https://support.google.com/a/answer/166852?hl=pl
Przy okazji warto przemyśleć powiązanie mailer'a z nowo zaimplementowanymi notyfikacjami.

**Comment by kuba-kazimierczak** [comment]
Od siebie dodam: aplikacja notifications oparta jest o wspomniany wyżej `mailer` obsługuje tylko najprostsze przypadki wysyłki, w szczególności nie ma możwliości podania pól `cc` ani `bcc`.

**Comment by jasiekmarc** [comment]
Problem został chyba rozwiązany.
