### ISSUE TITLE
Lista zapisanych do grupy studentów jako PDF

### ISSUE THREAD

**Issue by tilk** [iiuni/projektzapisy#648]
W poprzedniej wersji można było pobrać listę zapisanych studentów w formie ładnego i czytelnego PDF do druku. Korzystałem z tej opcji często, aby mieć gotową listę studentów do zapisywania notatek (np. zdobytej liczby punktów za zadania) w trakcie zajęć. Najwyraźniej opcja ta zniknęła.

**Comment by jasiekmarc** [comment]
Tuż po zamknięciu zapisów będę merge'ował duże zmiany wizualne w systemie (#603). Przy okazji myślę, że można zrobić coś podobnego.

Widok grupy — normalnie wyglądający tak:
![image](https://user-images.githubusercontent.com/5896456/53879914-ef00b980-400f-11e9-82e5-ac79552f00e2.png)

Na wydruku (po naciśnięciu Ctrl+P) wyglądałby tak:
![image](https://user-images.githubusercontent.com/5896456/53880080-5dde1280-4010-11e9-8643-ec74b4438772.png)

Czyli, widoczna by była wyłącznie tabelka zapisanych do grupy. Czy to by odpowiadało Twoim potrzebom?

**Comment by tilk** [comment]
Tak, dobrze zrobiony CSS dla wydruków załatwi sprawę.
