### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#65]
W projekcie jest bardzo dużo "magicznych stałych", np:

``` python
def is_proposal(self):
    return (self.status == 0) or (self.status == 5)
```

Powinniśmy zamienić je na stałe zdefiniowane w odpowiednich klasach.

**Comment by jasiekmarc** [comment]
Issue jest ogólną pretensją. Pewnie _magic numbers_ dalej w różnych miejscach występują, ale raczej je redukujemy.
