### ISSUE TITLE
Rozszerzenie modeli o identyfikatory z USOS

### ISSUE THREAD

**Issue by cahirwpz** [iiuni/projektzapisy#653]
Podobnie jak w #646 należy dodać pola, które wyznacza powiązanie 1:1 między obiektami z USOS i SZ.

* `Semester` pole `usos_kod` typ `Varchar(20)` (USOS: `DZ_CYKLE_DYDAKTYCZNE.KOD`)
* `Classroom` pole `usos_id` typ całkowity (USOS: `DZ_SALE.ID`)
* `Course` pole `usos_kod` typ `Varchar(20)` (już jest zatem należy tylko wystawić przez REST API) (USOS: `DZ_PRZEDMIOTY.KOD`)
* `Student` pole `usos_id` typ całkowity (USOS: `DZ_STUDENCI.ID`)
* `Term` pole `usos_id` typ całkowity (USOS: `DZ_TERMINY.ID`)
* `Group` pole `usos_nr` typ całkowity (USOS: `DZ_GRUPY.NR`)

W razie wątpliwości proszę pytać.

@jasiekmarc Nie potrzebuję wszystkich pól z podanych modeli do odczytu. Gdyby był sens ograniczać ich widoczność to listę można wywnioskować ze skryptów `powiaz_*.py` w repozytorium [iiuni/usos](https://github.com/iiuni/usos/blob/master/zapisy-to-usos).

Poniżej podaję listę modeli wykorzystywanych w skrypcie do migracji:
```
from apps.enrollment.courses.models.course import Course
from apps.enrollment.courses.models.group import Group
from apps.enrollment.courses.models.semester import Semester
from apps.enrollment.courses.models.term import Term
from apps.enrollment.courses.models.points import PointsOfCourseEntities, PointTypes
from apps.enrollment.records.models import Record
```

Wystawienie REST API dla nich uniezależniłoby mnie od posiadania lokalnej kopii bazy danych zapisów.

**Comment by jasiekmarc** [comment]
W tym momencie model `Course` nie ma pola `usos_kod`. Jest takie pole w modelu `CourseEntity` (podstawie przedmiotu). Czy potrzebujesz go także w `Course`? Czy potrzebujesz API dla `CourseEntity`?

**Comment by cahirwpz** [comment]
Hmm... to dobre pytanie. Wiemy, że:

 * `Course` to odpowiednik `DZ_PRZEDMIOTY` (klucz `KOD`)
 * `CourseEntity` to odpowiednik `DZ_PRZEDMIOTY_CYKLI` (klucz `(PRZ_KOD, CDYD_KOD)`, tj. kod przedmiotu i kod cyklu dydaktycznego)

Wydaje mi się zatem, że `Course` powinien mieć pole `usos_kod`. Z drugiej strony być może poszczególne edycje tego samego przedmiotu `CourseEntity` czasami są innymi przedmiotami w USOS (historycznie). Chyba trzeba by było zamienić na ten temat parę słów.
