### ISSUE TITLE
Zakładka dezyderaty nie wyświetla się na wszystkich podstronach

### ISSUE THREAD

**Issue by lewymati** [iiuni/projektzapisy#692]
Na podstronie:
https://zapisy.ii.uni.wroc.pl/offer/
zakładka 'dezyderaty' się nie wyświetla.

Z kolei na podstronie:
https://zapisy.ii.uni.wroc.pl/prefs/
jest już ona widoczna.

Powodem jest prawdopodobnie to, że zmienna `semester` nie zawsze jest przekazywana do widoku:
https://github.com/iiuni/projektzapisy/blob/master-dev/zapisy/templates/offer/base.html#L28

Dobrze, gdyby ten problem został rozwiązany zanim powiadomię pracowników o otwarciu dezyderat.

**Comment by jasiekmarc** [comment]
@lewymati Naprawiłem to poprzez wyświetlanie pracownikom tej zakładki zawsze.
