### ISSUE TITLE
Filtrowanie przedmiotów poddanych pod głosowanie

### ISSUE THREAD

**Issue by mzr** [iiuni/projektzapisy#704]
Miło by było, gdyby dałoby się filtrować przedmioty poddane pod głosowanie (np. w panelu głosowanie gdzie przydziela się punkty, oraz w panelu "podsumowanie głosowania").

**Comment by jpszczolowski** [comment]
Zgadzam się, głosowanie na studiach II stopnia byłoby o wiele przyjemniejsze, gdyby dało się odfiltrować wszystkie I1, K1, proseminaria etc.

**Comment by mzr** [comment]
^ Prawda. Wychodzi na to, że głosując na studiach II stopnia chciałoby się odfiltrować większość przedmiotów.
