### ISSUE TITLE
Nieczytelne wyniki oceny

### ISSUE THREAD

**Issue by j-michaliszyn** [iiuni/projektzapisy#705]
Tekstowe wypowiedzi w ocenie zajęć są w znaczniku "pre", który nie zawija wierszy, przez co nie da się ich wygodnie czytać. Proponuję zamienić "pre" na "spam", przykład na obrazku.

![ocena](https://user-images.githubusercontent.com/20044544/59666518-44269c80-91b5-11e9-838b-fec839f30b8a.png)

**Comment by jasiekmarc** [comment]
Ocena jest w tej chwili pisana całkowicie od nowa. Wyświetlanie wyników również.

**Comment by KGuzikowski** [comment]
Jestem nowy w projekcie :) Jaki url ma strona, której dotyczy ten wątek?

**Comment by tilk** [comment]
Na przykład:
https://zapisy.ii.uni.wroc.pl/grade/poll/341/poll_results/S6719

**Comment by tilk** [comment]
👏
