### ISSUE TITLE
Brak e-maila z informacją o nowym wpisie w aktualnościach

### ISSUE THREAD

**Issue by lekcyjna123** [iiuni/projektzapisy#734]
09.09.2019 o godzinie 23:55 Pan Mateusz Pyzik dodał w aktualnościach komunikat o rozpoczęciu korekty. Pomimo tego, że w ustawieniach powiadomień mam zaznaczone, że chcę być informowany e-mailowo o nowych wiadomościach w aktualnościach, żaden e-mail nie przyszedł do momentu w którym piszę to zgłoszenie. E-mail wpisany do SZ jest poprawny (mój uniwersytecki) i po ogłoszeniu Pani Małgorzaty Biernackiej z dnia 15.06.2019 powiadomienie przyszło normalnie.

**Comment by jasiekmarc** [comment]
Dziękuje za zgłoszenie. Faktycznie mamy problemy z mailami. Walczymy z tym.
