### ISSUE TITLE
Nie działa rezerwacja sal 

### ISSUE THREAD

**Issue by wcharatonik** [iiuni/projektzapisy#739]
Na lewo od sali powinien być zielony przycisk "wybierz" (podobny do "dodaj termin"), ale go nie ma. W zwiazku z tym nie da się nic zarezerwować.

Drobniejsze problemy: 
* po kliknięciu w "Dodaj termin" dostaję bezsensowny komunikat o błędzie "Please fill out this field" ze wskazaniem na (wypełnione) pole "Od" (dlatego godzina 09 na zrzucie ekranu jest na niebiesko)
* amerykański format daty (6 lutego na zrzucie ekranu) jest irytujący
file:///home/wch/Obrazy/Screenshot.jpg

**Comment by wcharatonik** [comment]
Sorry, screenshot nie dotarł
![Screenshot](https://user-images.githubusercontent.com/23313002/64874237-e6d2a800-d64a-11e9-91a7-5013697f3d89.jpg)

**Comment by jasiekmarc** [comment]
@wcharatonik: Jakiej używasz przeglądarki? Zarówno w Chrome jak i Firefoxie mam europejski format daty (być może to zależy od ustawienia języka w systemie?), a przyciski „wybierz” pojawiają się.

| Chrome (v76) | Firefox (v69) |
|------|-------|
| ![image](https://user-images.githubusercontent.com/5896456/64915194-3a83e500-d762-11e9-9371-ee0408318a6a.png) | ![image](https://user-images.githubusercontent.com/5896456/64915196-52f3ff80-d762-11e9-968b-026a8aee9094.png) |

Przypuszczam ponadto, że Twoja przeglądarka uważa pole „od” za niewypełnione, bo pole z godziną wyświetla w formacie z sekundami, a te zostawiłeś puste. Chrome i Firefox nie chcą sekund.

**Comment by wcharatonik** [comment]
Na dwóch desktopach (w pracy i w domu) mam firefoksa 60.9.0esr, oba komputery działają pod debianem stretch, i na obu mam takie objawy. Za to na laptopie (debian stretch, firefox 60.9.0esr)  mam przyciski wyboru sali i normalny format daty. Nic już z tego nie rozumiem. Na wszystkich komputerach locale ustawione na pl_PL.UTF-8.

[Godzinę później] Wyjaśniło się. Miałem zainstalowany, ale z jakiegoś powodu wyłączony dodatek z językiem polskim do firefoksa. Po ponownym włączeniu tego dodatku wszystko wróciło do normy. Można zamknąć.

**Comment by jasiekmarc** [comment]
Żeby wyjaśnić sprawę do końca: wydaje mi się, że Firefox oczekiwał uzupełnienia, czy godzina jest **AM**, czy **PM**. Po wpisaniu tego w okienko pojawiłyby się przyciski „wybierz”.
