### ISSUE TITLE
Błędna suma w głosowaniu

### ISSUE THREAD

**Issue by JMendyk** [iiuni/projektzapisy#742]
Próbowałem skontaktować się z administracją SZ mailowo przez `zapisy@cs.uni.wroc.pl`. Niestety nie dostałem odpowiedzi, może ktoś tutaj ma kontakt z administracją lub mógłby pomóc.

Treść wiadomości:

> Dzień dobry,
> 
> W czerwcu uczestniczyłem w głosowaniu na przedmioty i poprawnie wypełniłem formularz
> (w podsumowaniu głosowania jestem obecny na listach głosowania na przedmioty które wybrałem).
> Teraz, gdy w ramach korekty głosowania, stronę głosowania zastałem z komunikatem "Wykorzystano 20 z 15 punktów".
> Chciałbym upewnić się czy jest to błąd systemu głosowania.
> 
> Moje dane: Jakub Mendyk, nr indeksu <usunięto, można sprawdzić w systemie zapisów>
> 
> Pozdrawiam

**Comment by jasiekmarc** [comment]
Z tego co wiem, administrator @mpyzik bada sprawę.

**Comment by jasiekmarc** [comment]
Ostatecznie ja zbadałem sprawę. Chodzi o liczenie głosów na propozycje, które mają semestr _nieokreślony_ (co znaczy, że będą prowadzone w obu semestrach).

Jeszcze dzisiaj to naprawimy.
