### ISSUE TITLE
Korekta(?) "zczyściła" moje głosy na semestr letni

### ISSUE THREAD

**Issue by ApamNapat** [iiuni/projektzapisy#744]
Wziąłem udział w korekcie i teraz po kliknięciu "Pokaż mój głos" mam takie coś

![glosowanie](https://user-images.githubusercontent.com/18621228/64976020-9fe5ec00-d8b0-11e9-8733-605dd5655be7.png)

przy czym żaden z tych przedmiotów, jak można się spodziewać, nie pojawia się w korekcie na semestr zimowy (i wątpię, że każdy jeden został usunięty z oferty). Trochę to niepokojąco wygląda. To oczekiwane i mam czekać na korektę zimową czy bug?

**Comment by jasiekmarc** [comment]
Pewnie jest dobrze. W końcu korekty na semestr letni jeszcze nie było.

Może to kiedyś zmienimy na puste.
