### ISSUE TITLE
Filtrowanie po wielu rodzajach przedmiotu

### ISSUE THREAD

**Issue by mzr** [iiuni/projektzapisy#746]
Z tego co pamiętam, to kiedyś możliwe było wybranie wielu rodzajów przedmiotu jako filtr (np. filtr I2.T lub I2.Z). Obecnie nie jest to możliwe. Było to przydatne. 
Analogicznym ulepszeniem byłoby filtrowanie po wielu opiekunach przedmiotu.

**Comment by jasiekmarc** [comment]
To nie powinno być bardzo trudne. Filtry są zaprojektowane tak, by móc łatwo dodawać nowe rodzaje filtrów.

Może można by użyć takiego widgetu: https://vue-multiselect.js.org/.
