### ISSUE TITLE
Maile z HTML wysyłane są jako text/plain

### ISSUE THREAD

**Issue by hasparus** [iiuni/projektzapisy#749]
Cześć! Dostałem takiego maila jak na poniższym obrazku.

![image](https://user-images.githubusercontent.com/15332326/65219997-17d33280-daba-11e9-8728-f174067b9694.png)

Można założyć, że wszyscy studenci II czytają HTMLa, ale podejrzewam, że to nie jest zamierzone :) 

![image](https://user-images.githubusercontent.com/15332326/65219928-ee1a0b80-dab9-11e9-94c3-f2c1ebc2281a.png)

Wydaje mi się, że zamiast `Content-Type: text/plain` chcielibyście 

- wysyłać `Content-Type: multipart/alternative` z sekcjami `text/html` i `text/plain` 

albo

- usunąć htmlowe tagi z tej wiadomości, bo to tylko `br`y, więc można wymienić je na newline'y

**Comment by jasiekmarc** [comment]
Było (#738).
