### ISSUE TITLE
Brak możliwości zalogowania się przy użyciu USOS

### ISSUE THREAD

**Issue by lekcyjna123** [iiuni/projektzapisy#750]
Od jakiegoś czasu nie mam możliwości zalogować się do SZ przy pomocy konta USOS, w momencie gdy klikam zaloguj się, wyskakuje tylko opcja zalogowania się przy użyciu konta w SZ (a takiego nie posiadam). Błąd ten występuje tylko na Linuxie, na Windows 7 (edit: z Firefox Quantum 60.9.0esr) mogę zalogować się normalnie. Używam Ubuntu 18.04.3 i Firefoxa Quantum 69.0 (z tego co sprawdzałem najnowsza wersja).

![Zrzut ekranu z 2019-09-19 18-19-05](https://user-images.githubusercontent.com/34948061/65262225-29dcc180-db0a-11e9-91d4-04fbcd855ff5.png)

**Comment by jasiekmarc** [comment]
Proszę dla pewności spróbować system zapisów w przeglądarce z wyłączonymi dodatkami Adblock i NoScript. Być może któryś z nich ukrywa ten przycisk?

**Comment by lekcyjna123** [comment]
Rzeczywiście, AdBlock blokuje. Zalicza ten element do opcji "Blokowanie śledzenia przez media społecznościowe".
Przepraszam za kłopot.
