### ISSUE TITLE
Wyczyszczenie ciasteczek powoduje endless loop

### ISSUE THREAD

**Issue by pzmarzly** [iiuni/projektzapisy#757]
Błąd prawdopodobnie spowodowany pobieraniem powiadomień.

Wideo: https://youtu.be/3q23E7Oyt5A

Screenshot z ZAP-a (zaproxy) - request przed wyczyszczeniem cookies i po:

![DeepinScreenshot_select-area_20190927233333](https://user-images.githubusercontent.com/8074163/65803620-6306d880-e17f-11e9-9b52-50cd9c1ce750.png)

Testowane na Firefoxie, zarówno z włączonym blokowaniem trackerów, jak i bez. Wyświetlana liczba powiadomień może być wielkością strony logowania (od wyniku z ZAP-a trzeba odjąć rozmiar nagłówków).

https://github.com/iiuni/projektzapisy/blob/f1282624de12865cb54add664e3c8805026b0284/zapisy/apps/notifications/assets/components/Widget.vue#L34-L47

**Comment by jasiekmarc** [comment]
Dziękuję za zgłoszenie. Ciekawy _corner-case_. Ładnie Pan go zdiagnozował.

**Comment by pzmarzly** [comment]
Właściwie dalej nie wiem, skąd bierze się 100% użycia CPU. Myślę, że winowajcą może być parsowanie do `NotificationsDict`, ale chętnie się dowiem (choć oczywiście do rozwiązania problemu nie jest to potrzebne).

PS. `created()` nie musi być `async`, bo nie `await`-uje, dobrze myślę?

**Comment by jasiekmarc** [comment]
Co ciekawe, problem ten nie występuje w prototypie planu, a mógłby.
