### ISSUE TITLE
Usunięcie relacji „classroom” z modelu Term

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#770]
Pole `classroom` ewidentnie zostało zastąpione polem `classrooms` i powinno być usunięte, bo wprowadza programistów i administratorów w błąd.

https://github.com/iiuni/projektzapisy/blob/5b1106daa55fc7d71d32a7def4ee7630f3103591/zapisy/apps/enrollment/courses/models/term.py#L23

**Comment by bartektroszka** [comment]
Chciałbym się zapisać do tego zadania
