### ISSUE TITLE
Anachroniczne pola w modelu użytkownika

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#772]
Od kiedy mamy nowy system powiadomień (#701), pola preferencji powiadomień w modelu `BaseUser` nie mają efektu i należy je usunąć.

https://github.com/iiuni/projektzapisy/blob/5b1106daa55fc7d71d32a7def4ee7630f3103591/zapisy/apps/users/models.py#L34

**Comment by adam91091** [comment]
Pull request for this issue is already open:
https://github.com/iiuni/projektzapisy/pull/786

**Comment by jasiekmarc** [comment]
Closed by #786.
