### ISSUE TITLE
Kolacja po polsku

### ISSUE THREAD

**Issue by lgpawel** [iiuni/projektzapisy#776]
Obecnie sortowanie nazwisk albo ignoruje polskie diakrytyki (https://zapisy.ii.uni.wroc.pl/users/students/ lub https://zapisy.ii.uni.wroc.pl/users/employees/All/), albo traktuje je jako późniejsze leksykograficznie niż litery bez diakrytyk (spisy studentów w grupach). Tymczasem zachowanie powinno być takie samo we wszystkich przypadkach i, oczywiście, zgodne z polskim porządkiem słownikowym, w którym l < ł < m.

**Comment by jasiekmarc** [comment]
Duplikat #769.
