### ISSUE TITLE
Brak procentowego rozłożenia punktów ECTS z tagów dziedzinowych

### ISSUE THREAD

**Issue by lukdz** [iiuni/projektzapisy#777]
Na stronie przedmiotu np.:
https://zapisy.ii.uni.wroc.pl/courses/algorithms-for-big-data-201920-zimowy
mamy wymienione tagi dziedzinowe w tym przykładzie "PD (przetwarzanie danych) DS (Data Science)", nie mamy jednak informacji ile punktów przypada na który tag.

**Comment by jasiekmarc** [comment]
Zmiana ta nastąpiła w https://github.com/iiuni/projektzapisy/pull/694. Wydaje mi się, że w nowym programie studiów zrezygnowano z procentowego rozłożenia tagów. Przedmiot po prostu ma tag albo go nie ma.

**Comment by lukdz** [comment]
Jeśli dobrze rozumiem "nowy program" studiów dotyczy tylko nowych studentów. Na uczelnie chodzi jeszcze sporo osób wg. starego programu, którego wymagania muszą w dalszym ciągu spełnić. 
I dla nich taka wiedza była by przydatna.
