### ISSUE TITLE
Prace dyplomowe niedostępne dla użytkownika niebędącego pracownikiem ani studentem

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#803]
Pracownicy dziekanatu potrzebują dostępu do systemu pracy dyplomowych. Niestety, system wita ich następującym ekranem:
![image](https://user-images.githubusercontent.com/5896456/69718332-5c102e00-110e-11ea-938f-4eb66e59ab02.png)

Błąd rzucany jest w tym miejscu:
https://github.com/iiuni/projektzapisy/blob/0dec362be5b0106ea8bc5f230f0721b0d4604a01/zapisy/apps/theses/serializers.py#L343
a wynika z tego, że jednak są użytkownicy, którzy nie są ani pracownikami, ani studentami:
https://github.com/iiuni/projektzapisy/blob/0dec362be5b0106ea8bc5f230f0721b0d4604a01/zapisy/apps/theses/serializers.py#L334-L335

**Comment by jasiekmarc** [comment]
Rozwiążemy problem dodając pracownikom dziekanatu profil pracownika.

**Comment by user-45-20** [comment]
Optymalnym rozwiązaniem byłoby prawdopodobnie dodanie nowej klasy użytkownika, która reprezentuje pracowników niebędących kadrą naukową; ich poziom uprawnień to - prawdopodobnie - dostęp tylko do odczytu do wszystkich prac (w odróżnieniu od studentów, którzy mają dostęp wyłącznie do prac już zaakceptowanych, zatem nie można by tutaj użyć tej samej kategorii użytkownika).

Prawdopodobnie więc należałoby zmienić nazwę `REGULAR_EMPLOYEE` na `ACADEMIC_EMPLOYEE` i dodać coś w rodzaju `DEANS_OFFICE_EMPLOYEE`. Oczywiście, trzeba by dodać to również po stronie aplikacji przeglądarkowej. Chyba pokusiłbym się wtedy o zmianę modelu uprawnień; w tej chwili backend mówi aplikacji, jaki typ użytkownika korzysta z aplikacji, zaś aplikacja sama postanawia, czy danemu typowi użytkownika wolno np. głosować. Przy takiej liczbie różnych profili o różnych uprawnieniach być może prościej byłoby zwracać słownik z uprawnieniami:

```
{
  "can_view_not_accepted_theses": false,
  "can_add_new_theses": true,
  "can_vote_on_theses": false
  ...
}
```

Dodanie pracownikom dziekanatu profilu pracownika poskutkuje (w kontekście systemu prac dyplomowych) nadaniem im praw tworzenia i edycji swoich własnych prac, którego pewnie nie potrzebują. Nie będą mieć natomiast możliwości edycji prac stworzonych przez innych.

Jeżeli te dodatkowe uprawnienia nie są problemem, to wydaje się to być najlepszym rozwiązaniem, chyba, że spowoduje to nadaniem tym pracownikom niepożądanych uprawnień w innych modułach SZ.
