### ISSUE TITLE
Przedawnione maile z powiadomieniami

### ISSUE THREAD

**Issue by mbronek7** [iiuni/projektzapisy#805]
Jakiś problem z kolejkowaniem jobów? (Nwm w sumie jak to działa)
<img width="941" alt="Zrzut ekranu 2019-12-3 o 15 28 15" src="https://user-images.githubusercontent.com/23109826/70059838-c11dc500-15e1-11ea-836d-15314df0514f.png">

**Comment by jasiekmarc** [comment]
To trochę zaskakujące. Na pewno oba maile są tej samej treści? Nie ma Pan dwóch kont w Systemie Zapisów?
Czy ma Pan też dwa powiadomienia tej samej treści pod dzwoneczkiem?

**Comment by mbronek7** [comment]
Przepraszam źle się wyraziłem poprzedniego maila dostałem w listopadzie.

**Comment by jasiekmarc** [comment]
Jest faktycznie problem z limitami na Gmailu, który powoduje, że czasem wysłanie maila kończy się błędem. Wtedy zaległy mail zostanie wysłany przy następnej okazji. Przypuszczam, że wpadliśmy w taki przypadek.

Mamy plan rozwiązania tego problemu.

**Comment by matpyz** [comment]
Wraz z nową infrastrukturą wdrożeń problem został rozwiązany.
