### ISSUE TITLE
Dezyderaty wypełniane w złym semestrze

### ISSUE THREAD

**Issue by wiura** [iiuni/projektzapisy#813]
Dezyderaty na semestr lato 2020 zapisały się w systemie zapisów w semestrze zima 2019. Jest to mylące. Powinny się zapisać w semestrze, którego dotyczą.

**Comment by jasiekmarc** [comment]
Problem polega na tym, że otworzyć formularz dezyderat dla pracowników da się wyłącznie na aktualnie trwający semestr.

**Comment by jasiekmarc** [comment]
Prawdę mówiąc w ogóle nie ma sensu, żeby dezyderaty zależały od semestru. Powinny być jedne dezyderaty.

**Comment by jasiekmarc** [comment]
@wiura Gosiu, dokonałem pewnych zmian w dezyderatach (#904). Tak jak planowałem wcześniej, nie zależą one od semestru. W związku z tym dla jednego pracownika istnieje tylko jedna instancja dezyderat, a w API zniknęło pole `semester`.
