### ISSUE TITLE
Przepadające punkty za głosowanie na przedmiot, który nie trafił do oferty

### ISSUE THREAD

**Issue by ApamNapat** [iiuni/projektzapisy#823]
Na początku roku zagłosowałem na 3 przedmioty, które z tego co widzę nie znalazły się ostatecznie w ofercie: Graph Databases (1), Seminar: Software Engineering (1) i Proseminarium: Historia informatyki (3), ale w korekcie do rozdysponowania dostałem tylko dwa punkty zamiast pięciu. Możliwe, że jest to związane z tym, że Historia informatyki wypadła z oferty bardzo niedawno (tak sugeruje TWI). Jeśli nie jest to problem po stronie aplikacji to do kogo mogę się zwrócić po moje brakujące punkty?

**Comment by jasiekmarc** [comment]
W semestrze letnim zorganizowano przedmiot, który w ofercie figurował jako _zimowy_, przez co punkty za niego liczą się do korekty (gdzie głosuje się na instancje przedmiotów), ale nie do pierwotnego głosowania (gdzie głosowało się na propozycje).
Pani dyrektor zmieniła propozycję na _semestr nieokreślony_, co powinno rozwiązać problem.
