### ISSUE TITLE
Wyświetlanie daty i czasu w rezerwacji sal

### ISSUE THREAD

**Issue by tilk** [iiuni/projektzapisy#825]
W formularzu rezerwacji sali datę i czas wprowadza się w formacie amerykańskim (MM/DD/YYYY), a godziny w standardzie 12-godzinnym z AM/PM. Byłoby dużo naturalniej dla polskich użytkowników, którzy chyba stanowią tutaj większość, aby format daty był polski (DD.MM.YYYY) lub chociaż międzynarodowy ISO 8601 (YYYY-MM-DD), a czasu - 24-godzinny.
Na liście terminów egzaminów daty są pisane po angielsku.

**Comment by barnij** [comment]
> Na liście terminów egzaminów daty są pisane po angielsku.

Są pisane po angielsku, gdy język przeglądarki ustawiony jest na angielski i pisane po polsku, gdy język przeglądarki ustawiony jest na polski.

> aby format daty był polski (DD.MM.YYYY) lub chociaż międzynarodowy ISO 8601 (YYYY-MM-DD), a czasu - 24-godzinny.

![Screenshot 2020-02-06 00-46-45](https://user-images.githubusercontent.com/26609577/73893559-4d669580-487a-11ea-9e64-dc13bc55ca39.jpg)

Dziwne, u mnie działa.

**Comment by tilk** [comment]
> Są pisane po angielsku, gdy język przeglądarki ustawiony jest na angielski i pisane po polsku, gdy język przeglądarki ustawiony jest na polski.

To chyba niedobrze? Nic innego na stronie nie wskazuje na to, że miałaby ona być w języku angielskim. Albo lokalizować wszystko, albo nic.
Ale tak, rzeczywiście przeglądarkę mam bez polskiej lokalizacji, lecz locale systemowe jest polskie.

> Dziwne, u mnie działa.

A u mnie nie.
![Zrzut ekranu z 2020-02-06 17-11-39](https://user-images.githubusercontent.com/509167/73957183-4c7b4580-4906-11ea-9daf-94b36096c7d2.png)
To jest pewnie ten sam problem.

**Comment by lgpawel** [comment]
Chciałem zgłosić to samo, ale tilk mnie ubiegł, za to zauważyłem jeszcze literówkę (a nawet dwie - "lokalizaje" zamiast "lokalizację") w tekście pod polem wyboru lokalizacji.

**Comment by jasiekmarc** [comment]
To nie jest literówka. Można zarezerwować wiele sal.

**Comment by lgpawel** [comment]
Racja, ale brak "c" nadal jest literówką.

**Comment by receek** [comment]
Literówka poprawiona.

**Comment by receek** [comment]
Literówka poprawiona.

**Comment by receek** [comment]
Literówka została poprawiona.
Odnośnie dat nie możemy nic zrobić. Ogranicza nas standard HTML. Format dat jest zależny od ustawień językowych przeglądarki.
https://stackoverflow.com/a/9519493
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#Value
