### ISSUE TITLE
Problem z dodaniem rezerwacji

### ISSUE THREAD

**Issue by tilk** [iiuni/projektzapisy#826]
Użyłem w aplikacji Sale opcji Rezerwuj, ale popełniłem błąd dodając termin, więc usunąłem go, dodałem właściwy i kliknąłem Zapisz. W efekcie powstała rezerwacja podpisana "12:00 - 15:00, Sala 119", gdzie 119 nie jest linkiem. Sala nie została oznaczona jako zarezerwowana w tym terminie. Nie znalazłem możliwości edycji rezerwacji. Dodałem więc nową, na ten sam termin, i jest ona podpisana "12:00 - 15:00, sala 119", gdzie 119 jest linkiem, a słowo "sala" pisane jest z małej, a nie wielkiej litery.

**Comment by jasiekmarc** [comment]
Jak piszesz „jest ona podpisana” to masz na myśli jakąś listę rezerwacji? Zakładkę „Historia”?

(pytam, bo nie umiem korzystać z tego modułu do rezerwowania sal, a próbuję się wgryźć w problem)

**Comment by tilk** [comment]
Mam na myśli listę egzaminów (kartę "Egzaminy").

**Comment by tilk** [comment]
Nie udało się nam zreprodukować problemu.
