### ISSUE TITLE
Tagi HTML widoczne w powiadomieniach

### ISSUE THREAD

**Issue by barnij** [iiuni/projektzapisy#829]
Powiadomienia o dodaniu nowej wiadomości w aktualnościach, wyświetlają także tagi HTML obecne w wiadomości.

![Screenshot 2020-02-04 00-02-26](https://user-images.githubusercontent.com/26609577/73698551-c383c480-46e1-11ea-8bfa-a495c598c560.jpg)

**Comment by jasiekmarc** [comment]
Format newsów zmienił się z HTML-a na plaintext (#795). Powiadomienia, które jeszcze siedzą w redisie są w starym formacie, ale nowe już nie będą miały tagów.
