### ISSUE TITLE
Błąd w prototypie? - Health insurance mathematics

### ISSUE THREAD

**Issue by barnij** [iiuni/projektzapisy#831]
Przedmiot Algorytmy i struktury danych (L) zniknął z paska bocznego prototypu, zamiast niego widoczny jest podwójnie matematyczny przedmiot Health insurance mathematics.

![Screenshot 2020-02-04 01-09-42](https://user-images.githubusercontent.com/26609577/73701845-262d8e00-46eb-11ea-82e0-33b86b744384.jpg)

![Screenshot 2020-02-04 01-06-59](https://user-images.githubusercontent.com/26609577/73701853-288fe800-46eb-11ea-9621-273a66689a19.jpg)

**Comment by jasiekmarc** [comment]
@matpyz twierdzi, że nie błąd w prototypie.
