### ISSUE TITLE
Problem z kluczami do oceny zajęć

### ISSUE THREAD

**Issue by Mateque89** [iiuni/projektzapisy#833]
Już 3 raz z kolei podczas wydarzenia jakim jest "Ocena Zajęć" spotykam się z dziwnym bugiem. Polega on na tym że klucze które mi generuje nie są prawidłowe (struktura samych kluczy nie różni się od kluczy innych), aczkolwiek klucze nie działają i w obecnej edycji po wprowadzeniu klucza wyrzuca mi poniższy error:

> Błąd 500
Wystąpił błąd w naszym oprogramowaniu.
Szczegóły błędu zostały zapisane w logu serwisu, a administratorzy zostali powiadomieni, ale jeżeli posiadasz dodatkowe informacje, które pomogą namierzyć przyczynę problemu, stwórz nowy problem na trackerze Zapisów.

**Comment by jasiekmarc** [comment]
See #832.
