### ISSUE TITLE
Brak licencji w projekcie

### ISSUE THREAD

**Issue by user-45-20** [iiuni/projektzapisy#838]
W projekcie nie została określona żadna licencja; jeżeli dobrze rozumiem [wskazówki GitHub-a](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license), oznacza to, że - w teorii - nikt nie ma prawa korzystać z kodu Zapisów gdzie indziej.

Skoro Zapisy stały się _open source_, może warto na to zezwolić? Licencję z reguły określa się w pliku `LICENSE(.txt)`.

**Comment by jasiekmarc** [comment]
Sprawa jest bardziej skomplikowana. Jeśli byśmy się chcieli zdecydować na jakąś licencję, musielibyśmy to skonsultować z jakimiś prawnikami Uniwersytetu — bo za System poniekąd płaci Uniwersytet i ma do niego jakieś prawa (ale jakie dokładnie, to nie jest takie oczywiste). No i oczywiście znalezienie kogoś, kto jednocześnie jest władny podjąć taką decyzję i rozumie licencje oprogramowania jest niemożliwe (a jakby się znalazł, to nie będzie się zajmował takimi głupotami).

No a w praktyce, to jedyni potencjalni zainteresowani użyciem naszego systemu zapisów to instytucje podobne do naszej. I jeśli ktoś w takiej instytucji podejrzy, że mamy fajny system zapisów i oni by chcieli skorzystać, to jedyną praktyczną drogą jest odezwanie się do kogoś od nas — niezależnie od licencji oprogramowania. Jeśli zainteresowanie będzie autentyczne, to jesteśmy w stanie rozwiązać kwestie licencyjne.
