### ISSUE TITLE
Zła liczba bonusowych minut za ECTSy w zasadach

### ISSUE THREAD

**Issue by pzmarzly** [iiuni/projektzapisy#849]
Zhardcodowana wartość 5 minut:

https://github.com/iiuni/projektzapisy/blob/69832370b6bb8ce147a568d7f1e42aaa42ed84a0/zapisy/templates/help/rules.html#L17

Wartość rzeczywista 2 minuty:

https://github.com/iiuni/projektzapisy/blob/69832370b6bb8ce147a568d7f1e42aaa42ed84a0/zapisy/zapisy/settings.py#L272-L274

Zauważył: Michał Kucharczyk ([post](https://www.facebook.com/groups/Informatyka.UWr/permalink/2607382639493382/))

**Comment by jasiekmarc** [comment]
https://forum.iiuwr.me/t/otwarty-test-zmian-w-systemie-zapisow/1402/65

**Comment by AltairQ** [comment]
Nie rozumiem dlaczego to zgłoszenie zostało natychmiast zamknięte, przecież dotyczy ono niezgodności oficjalnej informacji na stronie ze stanem faktycznym w kodzie.

**Comment by pzmarzly** [comment]
@jasiekmarc To, że został zmniejszony bonus, nie jest problemem, ale dokumentacja systemu na https://zapisy.ii.uni.wroc.pl/help/rules/ nie opisuje rzeczywistego działania.

**Comment by jasiekmarc** [comment]
Ma Pan rację. Nie opisuje.
To też tłumaczyłem wczoraj na forum: https://forum.iiuwr.me/t/nieoficjalne-bonusy-do-czasu-zapisow/1722/2 przy innej okazji.

Jak jesteście w stanie sprawdzić, ostatnia merytoryczna zmiana w „pomocy” zaszła wieki temu (ja zrobiłem `git log` i nie znalazłem żadnych od 2012 roku). Oczywiście jest to niefortunne i kiedyś pewnie „pomoc” uaktualnimy albo zlikwidujemy, ale „pomoc” nie jest kontraktem wiążącym system zapisów. Jest porzuconą stroną internetową.
