### ISSUE TITLE
Błąd podczas zapisu na przedmiot kryptografia

### ISSUE THREAD

**Issue by konrad-wer** [iiuni/projektzapisy#855]
Jestem w kolejce do grupy ćwiczeniowej na przedmiot kryptografia, próbuję się zapisać do drugiej grupy ćwiczeniowej, w której jest jeszcze jedno wolne miejsce. Po wciśnięciu przycisku zapisz system wygląda tak jakby nastąpił zapis, jednak po odświeżeniu okazuje się, że nie jestem zapisany. W przypadku innych przedmiotów problem nie występuje.

**Comment by jasiekmarc** [comment]
To brzmi bardzo poważnie i niepokojąco. Próbuję zrozumieć, co się dzieje. Czy jest możliwe, że nie może się pan zapisać na ten przedmiot z powodu limitu punktów ECTS? Widzę, że nie jest pan zapisany na wykład, a przy zapisywaniu się do kolejki do tej pierwszej grupy powinno pana zapisać.

**Comment by konrad-wer** [comment]
Wypisałem się z kilku przedmiotów i dalej nie mogę, a na inne przedmioty zapisuję się bez problemu

**Comment by konrad-wer** [comment]
A nie przepraszam, na strukturę jądra unix mam ten sam problem

**Comment by jasiekmarc** [comment]
No a na ile ECTS-ów jest pan w sumie zapisany?

**Comment by konrad-wer** [comment]
Ok chyba, mój błąd bo teraz weszło, po wypisaniu się z wykładu z innego przedmiotu

**Comment by konrad-wer** [comment]
Przepraszam za zamieszanie, ale system nie daje czytelnej informacji co się dzieje

**Comment by jasiekmarc** [comment]
Wydaje mi się, że w powiadomieniach (z dzwoneczkiem) powinno się panu wyświetlić, czemu nie zapisało pana do grupy. Mylę się?

**Comment by konrad-wer** [comment]
Ok, prawda mój błąd, pojawią się powiadomienie. Jednak, wydaje mi się, że jest to mało czytelne, ponieważ jedyna wizualna informacja jaką dostaję w tej sytuacji to zwiększenie licznika przy dzwoneczku, co jak widać na przykładzie wątku, który tu rozpącząłem, łatwo przeoczyć i wziąć za błąd systemu (zwłaszcza w połączniu z faktem, że przez chwilę system wygląda tak jakbyśmy byli zapisani)
