### ISSUE TITLE
Niepotrzebna tabela w bazie danych.

### ISSUE THREAD

**Issue by jasiekmarc** [iiuni/projektzapisy#857]
W bazie danych jest tabela `south_migrationhistory`, która była chyba kiedyś używana do migracji (kiedy Django nie miało wbudowanego mechanizmu migracji) a teraz już nie jest potrzebna.

Jeśli w rzeczywistości tak jest, należy ją usunąć za pomocą migracji, a także zidentyfikować inne niepotrzebne tabele w bazie danych.

**Comment by Konrad-Kasprzyk** [comment]
W bazie danych mamy dwie niepotrzebne tabele. Pierwsza - `south_migrationhistory`. Jest to tabela nieużywana przez żadną zainstalowaną aplikacją w swoich modelach (`zapisy/settings.py INSTALLED_APPS`). Przez to nie można stworzyć migracji, która usunęłaby tę tabelę. Użycie `python manage.py syncdata`, wyrzuca błąd. Pozostaje usunąć tę tabelę ręcznie. Druga tabela to `auth_message`. Była ona używana przez Django1.x, obecnie używamy Django3.x. Jest więc ona bardzo przestarzała. Django nie może jej usunąć, gdyż nie wie o jej istnieniu. Tutaj tak samo pozostaje ręczne usunięcie tabeli. Lokalnie po usunięciu tych tabel wszystko działa. Testowałem dostęp do /fereol_admin, tworzenie nowego superuser, tworzenie nowej aplikacji, migracje i przeglądanie strony systemu zapisów.

Instrukcje jak usunąć tabele:
`python manage.py dbshell`
`DROP TABLE IF EXISTS south_migrationhistory;`
`DROP TABLE IF EXISTS auth_message;`
`exit`

**Comment by jasiekmarc** [comment]
A nie można by zrobić migracji, która odpala tego SQL-a?

**Comment by Konrad-Kasprzyk** [comment]
Dobra uwaga. Teraz tylko muszę wybrać której aplikacji stworzyć taką migrację.
