### ISSUE TITLE
Możliwość ukrycia zajęć w prototypie planu.

### ISSUE THREAD

**Issue by nerkulec** [iiuni/projektzapisy#860]
W prototypie planu można przypiąć zajęcia, na które uczęszczamy, ale nie jesteśmy zapisani.
Nie można jednak odpiąć/ukryć zajęć, na które jesteśmy zapisani, a nie uczęszczamy.
Taka możliwość byłaby szczególnie przydatna np. do odpięcia tutoringu.

EDIT: poprawiłem błąd nie zapisani -> zapisani

**Comment by jasiekmarc** [comment]
Rozumiem, że chodzi o zajęcia, na które **~nie~ jesteśmy zapisani**?

**Comment by nerkulec** [comment]
> Rozumiem, że chodzi o zajęcia, na które **~nie~ jesteśmy zapisani**?
Tak, poprawiłem
Chodzi o zajęcia, na które jesteśmy zapisani, a nie uczęszczamy. Przykłady:
-tutoring
-nudny wykład
-wirtualna pracownia

**Comment by jasiekmarc** [comment]
Muszę przyznać, że jestem nieco nieprzekonany.

Pani dyrektor dostaje w tym momencie niewyobrażalnie dużo maili od studentów, którzy przypadkiem wypisali się z jakiegoś przedmiotu (mimo że wypisanie z grupy wymaga potwierdzenia, że na pewno się chce to zrobić). Wyobrażam sobie te wszystkie maile studentów, którzy będą przekonani, że się z czegoś wypisali (albo że „przedmiot zniknął”).

Z drugiej strony nie widzę współmiernych korzyści. Trudno mi uwierzyć, że ma Pan tak napchany plan, że się Pan w nim nie może połapać.

**Comment by jasiekmarc** [comment]
Umówmy się tak: ja na razie zamknę to issue. A Pan może poszukać sojuszników, którzy mają chcieliby takiego ukrywania. Jeśli ich się trochę znajdzie, to zastanowimy się, czy da się to jasno i nieszkodliwie zrobić.
