### ISSUE TITLE
Nie można wydrukować przedmiotu z oferty 

### ISSUE THREAD

**Issue by j-michaliszyn** [iiuni/projektzapisy#863]
![pusty-druk](https://user-images.githubusercontent.com/20044544/75983402-c93f1680-5ee8-11ea-990f-79407fa5a2d7.png)

Zamiast zawartości strony https://zapisy.ii.uni.wroc.pl/offer/2482-logika-20-wybrane-tematy-teorii-modeli-skonczonych/ drukuje się pusta kartka, jak na screenshocie powyżej.

**Comment by jasiekmarc** [comment]
Nieprawda, nie drukuje się pusta kartka, tylko sylabus.
![Screenshot from 2020-03-05 13-57-49](https://user-images.githubusercontent.com/5896456/75983769-68640e00-5ee9-11ea-9bb4-ee605de124b2.png)

To jest specjalnie zrobione, żeby łatwo było drukować wypełnione przez pracowników sylabusy.
