### ISSUE TITLE
Uwagi i propozycje do widoku prac dyplomowych

### ISSUE THREAD

**Issue by wzychla** [iiuni/projektzapisy#887]
W widoku listy prac dyplomowych jako promotor widzę tytuł, typ i siebie jako promotora. Bardzo przydałaby się tam informacja o studencie (studentach) przypisanych do pracy.

Wybór studentów z listy wymagający skrolowania bardzo długiej listy uporządkowanej alfabetycznie (czego w pierwszej chwili nawet nie widać bo jako pierwsze na liście jest imię) jest bardzo niewygodny. O wiele wygodniejszy byłby input z datalist, a jak studentów jest dwóch lub więcej, to po stronie klienta + który dokłada kolejny input z tego samego datalist.

**Comment by jasiekmarc** [comment]
`<datalist>` niestety jest do kitu. Dziwiłem się, że ani Django ani Bootstrap go nie wspiera. Spróbowałem to zaimplementować od zera. Okazuje się, że poza brakiem `multiple` jest jeszcze brak rozróżnienia na to, co jest wyświetlone i co jest wysłane do serwera (a tego potrzebujemy). Trzeba to będzie jakimś Javascriptem skorzystać.

**Comment by wzychla** [comment]
Rzeczywiście trzeba trochę jscriptu dopisać. 

Brak możliwości podpięcia ID pod element wprost wynika z tego że tego nie ma zwykły input, pod który podepnie się datalist. Można to próbować obejść jakoś tak https://stackoverflow.com/a/29882539/941240. Pomysł jest tam prosty - do hidden inputa kopiuje się tekst z inputa, a jeśli przypadkiem to jest tekst zgodny z którymś z elementów datalist, to do tego ukrytego inputa przekopiowuje się ID. Na serwerze wiadomo wtedy czy to był wybór z listy (wtedy ma się ID) czy wybór spoza listy (wtedy ma się tekst - i można pokazać błąd walidacji).

Podobnie z wieloma wartościami, można dodać na życzenie nowe pole tekstowe z podpiętym tym samym datalist. Ale nawet to mogłoby być opcjonalne, wystarczyłoby jako default renredować takich pól więcej niż jedno (dwa? trzy?) żeby objąć 99% wszystkich przypadków (nie słyszałem nigdy o przypadku żeby autorów pracy było > 2, ale nie upieram się że takich przypadków nie ma, bo nie znam przepisów, które to regulują).

Moim zdaniem największa zaleta datalist jest taka że listę wyboru ogranicza na dopasowanie dowolnego podciągu, nawet ze środka słów z listy. W efekcie, jak na datainput byłyby pozycje postaci Jan Kowalski (123456) to nie ważne czy zacznę wpisywać Jan, czy Kowalski, czy 123456 albo nawet owalski, ski itd. to i tak na liście zobaczę ten element który chcę.

**Comment by jasiekmarc** [comment]
Zrobiłem już z dziesięć eksperymentów. Najbliżej sensownego rozwiązania byłoby [Select2](https://select2.org/), które da się połączyć z Django (https://github.com/applegrew/django-select2). Ale przez to, że tych studentów trochę jest, to muli to niemiłosiernie przeglądarkę.

Odkryłem za to, że taki `<select multiple>` jak mamy obecnie nie jest wcale taki koszmarnie niewygodny, bo działa na nim `Ctrl+F`. :grin:

**Comment by wzychla** [comment]
Faktycznie, ctrl+F tam działa dobrze, bo skroluje listę na właściwą pozycję. Pewnie nie tylko ja na to nie wpadłem, ale na szybko - to wystarczy tam wyżej label z tekstem że Ctrl+F działa.

Z tych dwóch propozycji wystarczy mi więc tylko godnosć studenta[ów] na liście prac.

**Comment by wzychla** [comment]
Czy z tym

_W widoku listy prac dyplomowych jako promotor widzę tytuł, typ i siebie jako promotora. Bardzo przydałaby się tam informacja o studencie (studentach) przypisanych do pracy._

mogę się przypomnieć?

**Comment by jasiekmarc** [comment]
Tak, zapomniałem o tym.

W jaki sposób ta informacja ma być umieszczona? Obecnie w tabelce jest po lewej stronie ptaszek mówiący, czy praca jest zarezerwowana, czy nie
![image](https://user-images.githubusercontent.com/5896456/85273406-d8d57180-b47d-11ea-9a66-913409e841a3.png)

Mogę na przykład zrobić tak, że nazwiska pojawiają się po najechaniu myszką na ptaszek — to nie zabierze przestrzeni w tabelce (istotne na urządzeniach mobilnych) ale wtedy nie będzie się po nich dało szukać Ctrl+F (ale mogę może dodać taki filtr).

**Comment by wzychla** [comment]
A jakby tak dać dodatkową kolumnę ale w niej nazwiska studentów każde w osobnej linii? Jako ostatnia kolumna? Tytuł mogłby się nawet zawijać, byleby mieć nazwiska studentów tam. 

Alternatywnie - autorzy i tytuł w jednej i tej samej kolumnie (tej najszerszej). Coś w stylu: Jan Kowalski: Implementing of an ..., z czego Jan Kowalski moze nawet być nieklikalne, a tylko tytuł pracy klikalny, jak teraz. Wtedy dodatkowy filtr byłby niepotrzebny.
