### ISSUE TITLE
[users] Obiekt "Program" określa stopień studiów na podstawie ciągu znaków

### ISSUE THREAD

**Issue by bpodrygajlo** [iiuni/projektzapisy#89]
Stopień studiów studenta określany jest tylko za pomocą ciągu znaków wpisywanego przez administratora zapisów. W modelu `Program` powinny znaleźć się odpowiednie pola określające stopień studiów (licencjackie/inżynierskie/magisterskie/doktoranckie) i typ (wieczorowe/dzienne/jednolite), etc.

**Comment by jasiekmarc** [comment]
Nie ma nic złego w tym, że program jest identyfikowany stringiem.
