### ISSUE TITLE
Popsuta nawigacja w ocenie przedmiotów

### ISSUE THREAD

**Issue by pzmarzly** [iiuni/projektzapisy#926]
Nawigacja na boku nie zgadza się z faktyczną kolejnością stron. Klikam na OEGI (2ga opcja od góry), przenosi mnie na `https://zapisy.ii.uni.wroc.pl/grade/poll/submissions/1/`, ale to jest RPiS (3cia opcja od góry):

![Screenshot from 2020-06-19 16-03-26](https://user-images.githubusercontent.com/8074163/85141216-b9083880-b246-11ea-8ba4-c6adabd0337b.png)

Nie jest to off-by-one, bo klikam na wykład RPiS (5te od góry), przenosi mnie na `https://zapisy.ii.uni.wroc.pl/grade/poll/submissions/4/`, ale to wykład PARO (8sma opcja od góry):

![Screenshot from 2020-06-19 16-03-37](https://user-images.githubusercontent.com/8074163/85141672-68450f80-b247-11ea-93c9-11c3cc92f686.png)

Wygląda jakby menu się źle sortowało. Możliwe że winna jest kombinacja wziętych przeze mnie przedmiotów, jeśli nie udało by się zreprodukować błędu, to mogę przesłać listę mailem.

**Comment by jasiekmarc** [comment]
Faktycznie, jestem w stanie ten błąd odtworzyć u siebie.
