### ISSUE TITLE
Wprowadzone klucze nie są w poprawnym formacie.

### ISSUE THREAD

**Issue by sikorsson** [iiuni/projektzapisy#928]
Tak jak w tytule, świeżo pobrane klucze nie działają przy ich wprowadzaniu przez co nie jestem w stanie ocenić zajęc.
![image](https://user-images.githubusercontent.com/58947592/85221459-33a29680-b3b4-11ea-9570-a4e575b905d8.png)

**Comment by jasiekmarc** [comment]
Klucze wygenerował Pan na stronie systemu zapisów, za pomocą skryptu Pythonowego, czy samodzielnie?
Wkleja Pan cały wygenerowany string czy po kawałku?

**Comment by sikorsson** [comment]
Klucze wygenerowałem w zakładce Pobieranie kluczy.
Próbowałem wklejać klucze na różne sposoby, od całości do fragmentów i w żadnym wypadku to nie działa.

**Comment by jasiekmarc** [comment]
Komunikat, który się Panu wyświetla pojawia się wyłącznie, gdy wklejone klucze nie są w poprawnym formacie JSON. Czy mógłby Pan je wkleić do jakiegoś validatora JSON, albo spróbować sparsować w konsoli JS w przeglądarce?

Jeśli skrypt w systemie zapisów faktycznie wypluł niepoprawne klucze, chciałbym zrozumieć, czemu tak się stało. Czy używa Pan jakiejś nietypowej przeglądarki, albo rozszerzeń, które robią coś dziwnego z JavaScriptem? Być może mógłby Pan wkleić te klucze **zastąpiwszy wartości w polach** `ticket` i `signature`.

**Comment by sikorsson** [comment]
Validator wyrzucił mi błąd.
Jeśli chodzi o przeglądarkę to korzystam z Chrome w Adblockiem i wtyczką Night Theme (zamienia jasne kolory na ciemne).
W załączniku wrzucam klucze (zmienione ticket i signature).
[ankieta.txt](https://github.com/iiuni/projektzapisy/files/4810327/ankieta.txt)

**Comment by jasiekmarc** [comment]
Zdumiewające. Nie wiem, czemu tak wyglądają Pana klucze. Uruchomiłem sobie własny serwer i wygenerowałem klucze, oczywiście moje wyszły poprawne (podobnie jak wielu studentom, którzy już ocenili zajęcia). Na razie zostawiam issue otwarte, a jak nikt inny się z takim problemem nie znajdzie, to zrzucimy na Pana Adblocka.

Jest w każdym razie jasne, jak może Pan poprawić to formatowanie. Zamiast
```
{
  tickets [
    {
      name Wykład Nieznany Prowadzący,
      type O ekonomii i gospodarce inaczej (w),
      id 7190,
      ticket 123,
      signature 123
    },
    ...
```
powinno być
```
{
  "tickets": [
    {
      "name": "Wykład Nieznany Prowadzący",
      "type": "O ekonomii i gospodarce inaczej (w)",
      "id": "7190",
      "ticket": "123",
      "signature": "123"
    },
    ...
```
Jak Pan to uważnie zrobi, system powinien zaakceptować klucze.
