### ISSUE TITLE
Błąd w trakcie konfigurowania projektu

### ISSUE THREAD

**Issue by barnij** [iiuni/projektzapisy#930]
Podczas stawiania Projektu Zapisów, jedno z zadań w playbooku ansible rzuca błędem i przez to nie pozwala na ukończenie konfiguracji.

Zadanie w pliku `ansible/postgres.yml,` które powoduje błąd:
```
- name: Apply migrates to empty database
      vars:
        ansible_python_interpreter: "{{ PYTHON }}"
      django_manage:
        command: migrate
        app_path: "/vagrant/zapisy"
        virtualenv: "/home/vagrant/env3"
```

Błąd:
```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "cmd": "./manage.py migrate --noinput",
    "invocation": {
        "module_args": {
            "app_path": "/vagrant/zapisy",
            "apps": null,
            "cache_table": null,
            "clear": null,
            "command": "migrate",
            "database": null,
            "failfast": false,
            "fixtures": null,
            "link": null,
            "liveserver": null,
            "merge": null,
            "pythonpath": null,
            "settings": null,
            "skip": null,
            "testrunner": null,
            "virtualenv": "/home/vagrant/env3"
        }
    },
    "msg": "\n:stderr: /usr/bin/env: ‘python\\r’: No such file or directory\n",
    "path": "/home/vagrant/env3/bin:/home/vagrant/env3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
    "syspath": [
        "/tmp/ansible_django_manage_payload_a_rp61h3/ansible_django_manage_payload.zip",
        "/usr/lib/python36.zip",
        "/usr/lib/python3.6",
        "/usr/lib/python3.6/lib-dynload",
        "/home/vagrant/env3/lib/python3.6/site-packages",
        "/home/vagrant/env3/lib/python3.6/site-packages/newrelic-2.68.0.50"
    ]
}
```

Tymczasowe rozwiązanie przed rozwiązaniem problemu:
1. Należy usunąć/zakomentować zadanie "Apply migrates to empty database" z pliku `ansible/postgres.yml`
2. Uruchomić klasycznie konfigurację za pomocą `vagrant up` lub `vagrant provision`.
3. Zalogować się na maszynę za pomocą `vagrant ssh`
4. Powinno być już aktywowane wirtualne środowisko, jeśli nie jest należy je aktywować: `. ~/env3/bin/activate`
5. Przejść do folderu `/vagrant/zapisy`
6. Zatrzymać usługę _runserver_: `sudo systemctl stop runserver.service`
7. Uruchomić migracje: `python manage.py migrate`
8. Uruchomić usługę _runserver_: `sudo systemctl start runserver.service`

**Comment by jasiekmarc** [comment]
Czy tu chodzi o to, że Ansible spróbował przeprowadzić migracje zanim Vagrant zamontował folder?

**Comment by barnij** [comment]
> Czy tu chodzi o to, że Ansible spróbował przeprowadzić migracje zanim Vagrant zamontował folder?

Nie sądzę, by to było to :/
