### ISSUE TITLE
Wybór ankiety otwiera inną ankietę

### ISSUE THREAD

**Issue by JMendyk** [iiuni/projektzapisy#931]
Wygenerowałem klucze do oceny zajęć jak co semestr. W sesji incognito przeglądarki wprowadziłem klucze i pomyślnie uzyskałem dostęp do znanego interfejsu:

<img src="https://user-images.githubusercontent.com/9089004/85632545-cd4d9a80-b677-11ea-933e-97cbbb89e179.png" width="80%">

Gdy jednak wybrałem kolejną ankietę, wyświetlona w głównej części ankieta nie odpowiada tytułem wybranej ankiecie z prawego panelu:

<img src="https://user-images.githubusercontent.com/9089004/85632677-0dad1880-b678-11ea-9890-6cac5b209708.png" width="80%">

Problem występuje także w kolejnych ankietach:
<img src="https://user-images.githubusercontent.com/9089004/85632626-f66e2b00-b677-11ea-9991-1ffa9cdf041d.png" width="80%">
<img src="https://user-images.githubusercontent.com/9089004/85632646-fec66600-b677-11ea-9658-c97a54fd4a02.png" width="80%">

Załączam otrzymany plik (ze zmienionymi ticket i signature):
[keys_for_issue.txt](https://github.com/iiuni/projektzapisy/files/4828122/keys_for_issue.txt)

Próbowałem zamienić kolejność wpisów by odzwierciedlić porządek widoczny na stronie - nie dało to jednak pożądanego efektu. Prawie na pewno nie było takiego problemu w poprzednich semestrach.

**Edit**: Delikatna poprawa czytelności.

**Comment by jasiekmarc** [comment]
Dziękuję. Problem został już zgłoszony #926 i naprawiony w #927. Nowy kod nie jest jeszcze wrzucony na serwer.

**Comment by jasiekmarc** [comment]
Teraz już nowy kod jest na produkcji. Problem powinien zniknąć.
