### ISSUE TITLE
Wczesne poprawki do aktualności nie są uwzględniane w powiadomieniach / mailach

### ISSUE THREAD

**Issue by lgpawel** [iiuni/projektzapisy#964]
Jeśli, jak domyślam się z timestampów, pomiędzy dodaniem nowej aktualności a pojawieniem się jej w powiadomieniach, upływa jakiś (ustalony?) czas, to powiadomienie / mail o niej mogłyby uwzględniać wczesne poprawki w treści, a tego chyba nie robią:

![Screenshot_2020-09-15_11-09-10](https://user-images.githubusercontent.com/16328696/93196890-44606f80-f74b-11ea-9385-7e7cc57a06d0.png)

(Strona ze skorygowaną treścią została załadowana tuż po otrzymaniu maila, a wg autora korekta została wprowadzona wcześnie.) Ponadto literówka była widoczna w dymku z powiadomieniami, ale wyczyściłem go bez udokumentowania :disappointed:

**Comment by jasiekmarc** [comment]
Nie ma żadnego intencjonalnego opóźnienia w wysyłaniu maili. Maile do wysłania trafiają do kolejki, która ma pewien lag ze względu na to, że inaczej Gmail nas banuje.

Ten lag będzie zresztą niedługo usunięty, bo już mamy gotową konfigurację serwera z własnym serwerem pocztowym. Czekamy tylko, aż administrator Systemu Zapisów ją zainstaluje.

**Comment by lgpawel** [comment]
A to, że powiadomienie stowarzyszone z aktualnością nie uwzględnia korekt w jej treści, też jest intencjonalne?

**Comment by jasiekmarc** [comment]
Do kolejki e-maili jest wrzucone powiadomienie z początkową treścią nowego newsa. Edycja istniejącego newsa nie powoduje wysłania nowych maili (to jest intencjonalne — ile można dostać maili o jednym newsie).

**Comment by lgpawel** [comment]
Mam na myśli powiadomienie w dymku na stronie, nie rozsyłane mailem, ale zgaduję, że _by design_ jest to jedno i to samo.
