### ISSUE TITLE
Niezgodność czasu T0 z liczbą ECTS przy przechodzeniu ze studia II stopnia

### ISSUE THREAD

**Issue by JMendyk** [iiuni/projektzapisy#975]
W tym miesiącu skończyłem studia ISIM i pomyślnie zrekrutowałem się na Informatykę (II stopień). W związku z tym w ciągu ostatnich kilkunastu dni czas T0, program studiów i liczba ECTSów przyjmowały co najmniej trzy wartości:

1. T0 = Poniedziałek 28 września 15:40, Program = ISIM, ECTSy = 190 (ok)
2. T0 = Poniedziałek 28 września 15:40, Program = Informatyka dzienne II stopnia, ECTSy = 180 (nie ok, zgaduję że 180 jest wpisane "z palca" po przejściu na II stopnień ale wtedy czas T0 jest zbyt wczesny)
3. T0 = Poniedziałek 28 września 16:00, Program = Informatyka dzienne II stopnia, ECTSy = 180 (ok)

Przy czym stan 2 był na pewno widoczny wieczorem 24 września, a stan 3 pojawił się przed 25 września 9:10.

Zdaję sobie sprawę z tego, że jest to dość graniczny przypadek (na dodatek wciąż jestem zapisany na studia inżynierskie I stopnia) ale system zapisów mógłby lepiej komunikować takie zmiany np. przez wysłanie maila że mój program/ECTSy/czas T0 uległ zmianie - szczególnie gdy dzieje się to na 7 godzin przed rozpoczęciem zapisów.

Mój numer indeksu: 301111

Z góry dziękuję za rozpatrzenie mojego zgłoszenia.

P.S.
Nie ma to miejsca w moim przypadku ale można wyobrazić sobie też sytuację, w której absolwent ISIM rozpoczyna studia II stopnia ale kontynuuje też studia inżynierskie *na których ma więcej niż 180 ECTSów* - czy w tej sytuacji "straci" ECTSy z inżynierskich co odbierze mu zasłużoną przewagę w rekrutacji czy raczej system zapisów bierze program o maksymalnej liczbie zdobytych ECTSów.

**Comment by matpyz** [comment]
1. Tymczasowe anomalie związane były z tym, że przeliczanie czasów nie następowało natychmiast po aktualizacjach.
2. Rzeczywiście, zdarzają się osoby o większej ilości punktów, i aktualnie trwają rozmowy jak to potraktować.

**Comment by jasiekmarc** [comment]
Sprawa do rozwiązania przez administratora systemu zapisów (i administratora USOS i dyrektora ds. dydaktycznych). Nie jest to błąd do naprawienia w samym systemie, więc pozwalam sobie zamknąć.
