### ISSUE TITLE
Niepoprawne linki w aplikacji Przydziały

### ISSUE THREAD

**Issue by mbuszka** [iiuni/projektzapisy#977]
Linki które powinny przekierować do odpowiednich sekcji strony (np. przydział według przedmiotów, przydziały dla konkretnej osoby itp.) przekierowują na stronę główną. Problem występuje na wersji produkcyjnej.

Przykładowo, klikając na 'przydział według przedmiotów' przechodzimy do `https://zapisy.ii.uni.wroc.pl/#section-by-course`,
a oczekiwany efekt otrzymalibyśmy przy przejściu na `https://zapisy.ii.uni.wroc.pl/offer/assignments/#section-by-course`

Wydaje mi się, że jest to kwestia brakującego kawałka ścieżki `offer/assignments` w linku.

**Comment by jasiekmarc** [comment]
Winna jest [ta linijka](https://github.com/iiuni/projektzapisy/blob/0e6f9f55dcce76d5aba1644548387b3045216d26/zapisy/templates/base.html#L12).

**Comment by jasiekmarc** [comment]
Ten problem występuje też w aplikacji `news` w paginacji:
https://zapisy.ii.uni.wroc.pl/news/ (na dole).
