### ISSUE TITLE
Eksport kalendarza do .ical

### ISSUE THREAD

**Issue by tilk** [iiuni/projektzapisy#987]
Dało się kiedyś wygenerować eksport .ical planu zajęć, co bardzo ułatwiało zaplanowanie zajęć w ramach semestru. Fajnie by było, gdyby taka opcja znowu była dostępna. A jeszcze fajniej by było, gdyby nie znikała w przyszłości bez ostrzeżenia.

**Comment by jasiekmarc** [comment]
Przecież jest.

**Comment by tilk** [comment]
Gdzie? Widzę tylko opcję "Eksportuj plan zajęć", która daje jakiś CSV. Załączam screenshot. Wskaż, co mam kliknąć, skoro jest.

![Zrzut ekranu z 2020-10-01 12-02-17](https://user-images.githubusercontent.com/509167/94795885-475f8f00-03de-11eb-8b69-bbcec4614b2e.png)

**Comment by jasiekmarc** [comment]
Racja, CSV, który można sobie zaimportować do Google Sheets.

**Comment by tilk** [comment]
Wiele narzędzi obsługuje iCal, a nie obsługuje CSV (Evolution na przykład).
