### ISSUE TITLE
Brak zajęć wirtualnych w eksporcie kalendarza

### ISSUE THREAD

**Issue by tilk** [iiuni/projektzapisy#988]
W pliku CSV eksportowanym z planu zajęć są tylko zajęcia posiadające przydzielone fizyczne sale.

**Comment by whiskeyo** [comment]
W bazie danych brakuje termów przedmiotów prowadzonych zdalnie. Naprawiłem wyszukanie grup, poprzednia wersja dopisywała do planu grupy z których już się wypisaliśmy.

**Comment by whiskeyo** [comment]
W pliku `zapisy/apps/schedule/models/term.py` w funkcji `create_course_terms` pętla tworzyła terminy dla każdej sali, jednak zajęcia zdalne nie miały przypisanej żadnej sali, przez co nie były tworzone dla nich termy. Poprawiłem ten błąd, a następnie tym skryptem zaktualizowałem wszystkie termy z bieżącego semestru, aby dodać brakujące, dzięki czemu w kalendarzu pojawiają się również zajęcia zdalne:
```
from apps.enrollment.courses.models.term import Term as CourseTerm
from apps.enrollment.courses.models.semester import Semester

semester = Semester.get_upcoming_semester()
courseTerms = CourseTerm.objects.filter(group__course__semester=semester)

for item in courseTerms:
    item.save()
```
