### ISSUE TITLE
Usunięcie wszystkich powiadomień przenosi na stronę główną

### ISSUE THREAD

**Issue by barnij** [iiuni/projektzapisy#992]
Jak w tytule.
![zapisy](https://user-images.githubusercontent.com/26609577/95402437-f97fe500-090f-11eb-93a9-95b92a1ecbd0.png)

**Comment by mbuszka** [comment]
@ketanx66 Czy po zmianach w #991 problem dalej występuje?

**Comment by ketanx66** [comment]
Nie, zostajemy na tej samej stronie
