### ISSUE TITLE
Indywidualne obliczanie czasów zapisu dla nowo-aktywowanych studentów.

### ISSUE THREAD

**Issue by matpyz** [iiuni/projektzapisy#997]
Obecnie, istnieje akcja `Oblicz czasy otwarcia zapisów`, dostępna z panelu admina `fereol_admin/courses/semester`, która wylicza czasy zapisów dla wszystkich aktywnych studentów.

Wydaje się kwestią refaktoryzacji istniejącego kodu udostępnienie w panelu `fereol_admin/users/student` akcji `Oblicz czasy otwarcia zapisów`, która obliczałaby czasy dla zaznaczonych studentów oraz procedury w Pythonie realizujacej to zadanie, do użycia w skryptach administratora.

Ma to zastosowanie w przypadkach "trudnych" (matematycy, wielokierunkowi i przeniesieni wykłócający się o bonus ECTS). W stanie obecnym, po aktywacji studenta, administrator wywołuje przeliczenie czasów dla wszystkich. Oprócz oczywistego marnotrawstwa czasu serwera, ma to skutek w nadpisaniu niestandardowych, ręcznie przygotowanych czasów w modelu `GroupOpeningTimes`, które mają zastosowanie przy zapisach pierwszego roku (gdy nie zapisujemy ich ręcznie, tylko dzielimy na tury zapisów). W praktyce, oznacza to, że czasy pierwszaków trzeba ponownie korygować ilekroć pojawi się student matematyki proszący o dostęp do systemu.

W mojej ocenie jest to zmiana kosmetyczna, jednak wydatnie usprawniająca działania administracyjne przed i podczas zapisów.

**Comment by jasiekmarc** [comment]
Sam postulat ma sens.

Podstawowe pytanie brzmi: czemu mamy **niestandardowe**, **ręcznie przygotowane** czasy otwarcia zapisów? Miało to jakiś sens, gdy robiliśmy tury, ale teraz z tur już zrezygnowaliśmy.

**Comment by matpyz** [comment]
W tym semestrze nie ma takich, jednak nie byłbym zaskoczony, gdyby powróciły tury po zakończeniu pandemii.
